### ISSUE TITLE
More information on Native References please

### ISSUE THREAD

**Issue by S1r-Lanzelot** [MicrosoftDocs/xamarin-docs#100]
I would like more information on Native Framework References please.... For example, when I add a Native Reference to a binding project, how do I know what Properties to set for the reference... Properties like: Linker Flags (where do I look to get this information for my iOS sdk?), Frameworks, Smart Link, and weak frameworks? Basically, I need to understand the properties section better for Native Framework References and I need to know where I can source the information for these property fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b705f33-37c3-65e6-13e2-64e15e759f62
* Version Independent ID: 3f5e7a5b-ba79-a40d-d7d5-0c1e4357b046
* Content: [Native References - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/native-references)
* Content Source: [docs/cross-platform/macios/native-references.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/native-references.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @S1r-Lanzelot, let me look in to this and see if there are any updates we should make to this doc. Thanks for the question.

**Comment by bradumbaugh** [comment]
Hi @S1r-Lanzelot, thanks for the question.

First up, [this video](https://youtu.be/DV7cGR0ySgo?t=1555) of Miguel speaking about Binding Objective-C libraries (from Evolve 2013) is helpful, as there's a discussion (starting at the time I linked to) about the various options you mentioned.

In order to determine what specific values to use for these fields, you'll need to check with the framework provider. The linker flags are passed to the native linker.

I'll add a note internally to call out these options in our binding docs.

Thank you!
Brad
