### ISSUE TITLE
“Tools > SDK Manager > Locations” Not Available On macOS?

### ISSUE THREAD

**Issue by varunpramanik** [MicrosoftDocs/xamarin-docs#1198]
SDK Manager doesn't appear to exist in the Tools menu on Visual Studio for Mac. Rather, the options are under the regular application preferences (Command + ,).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by vyedin** [comment]
Thanks! We will fix.

**Comment by vyedin** [comment]
Actually, the doc is correct. It exists in both locations. (I should remember, I wrote the spec for SDK manager).

<img width="425" alt="screen shot 2018-12-04 at 9 06 57 am" src="https://user-images.githubusercontent.com/1050709/49447280-1abb9b80-f7a4-11e8-94c1-6248dad82b21.png">

**Comment by varunpramanik** [comment]
Well, this is an honor. Thanks! I couldn't find it in my Tools menu, though I'm going to chalk it up to something I didn't opt to have installed during setup. I appreciate your responsiveness and time a great deal.

<img width="362" alt="screen shot 2018-12-04 at 8 59 11 am" src="https://user-images.githubusercontent.com/5219219/49450847-7f2a2b00-f7a3-11e8-827a-decb270411b0.png">

**Comment by OliverKohlDSc** [comment]
You need to install Xamarin.Forms at least for Android.

<img width="495" alt="screenshot 2018-12-11 at 21 05 46" src="https://user-images.githubusercontent.com/8104064/49827052-ac20a400-fd88-11e8-8269-8b426938da87.png">

After the installation the menu items will appear.

**Comment by varunpramanik** [comment]
I appreciate the tip, thanks!

**Comment by hugodahl** [comment]
I just ran into the same issue which @varunpramanik mentioned, both with VS 2019 for Mac, Preview 1 (v8.0 Build 869) as well as the current VS for Mac (v7.7.2 build 21).

The banner appears on launch, with the [Learn More](https://go.microsoft.com/fwlink/?linkid=2004274) link, `Start using now` and `Don't show again` buttons in both instances, however, the `SDK Manager` menu item doesn't appear.

I mention this because either the banner or the instructions in the docs could be misleading, and based on previous comments, the absence of the `SDK Manager` option is expected behaviour if no features depending on the JDK are available for the given instance of Visual Studio.

Given this, to prevent any further questions, the opening of new issues, or even having to refer to the comments or checking Github (for those who do in the first place), it may be worth taking one or several courses of action.

The first and likely most simple to implementation would be to add a note in the docs, that this menu option is only present if such features are available? Or alternate instructions/locations, such as the Options dialog, under `Projects` => `SDK Locations` => `Android` in the `Java SDK (JDK) Location` field, to prevent the banner from appearing, without clicking the `Don't show again" button, since that may lead to similar issues later on, or "miss out" on using the new JDK if, at some point in the future, the user enables a feature relying on the JDK.

Another option, albeit likely to be much more intrusive to the development process, would be to add logic determining whether to display the banner to the user or not, with its activation state re-evaluated whenever any features depending on the JDK are added or removed from the Visual Studio instance.

**Comment by conceptdev** [comment]
**SDK Manager** appears in the **Tools** menu whenever an Android workload option has been installed. If you continue to have issues please report them via Visual Studio's **Help** menu or on [developer community](https://developercommunity.visualstudio.com/spaces/8/index.html), thanks.
