### ISSUE TITLE
"File Not Found"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1213]
@EdwardCaulfield commented on [Sun Dec 02 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/20)

Attempting to install on Mac OS Mojave and even though I can set the path as documented in this guide, it still shows a "Not Found" error for the SDK location.  I am not at all successful in the NDK location and even though I am able to navigate to the Java SDK (JDK) Location and it gets a green "Found" - once I click on "OK" and return to the dialog, all fields are empty again.

I am using the version 7.7 (build 1868) of Visual Studio for Mac (Community edition).

Much appreciate your help clarifying this situation.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft Mobile OpenJDK-Verteilung (Vorschauversion) - Xamarin](https://docs.microsoft.com/de-de/xamarin/android/get-started/installation/openjdk)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

---

@vyedin commented on [Mon Dec 03 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/20#issuecomment-443834644)

@EdwardCaulfield would you mind filing this in VS Mac Report an Issue so we track it in our bug system? Please also attach your VS for Mac logs.

---

@EdwardCaulfield commented on [Mon Dec 03 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/20#issuecomment-443845524)

Will do.

---

@CeciAc commented on [Mon Dec 03 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/20#issuecomment-443861471)

Hi @vyedin @EdwardCaulfield 
Should I move this issue to the en-us repository?
Please advise,

Kind regards

---

@EdwardCaulfield commented on [Tue Dec 04 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/20#issuecomment-444053105)

Yes, please.

Kind Regards,

Edward

**Comment by conceptdev** [comment]
As indicated in the thread above, this should be reported via [Visual Studio for Mac report a problem](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem) page.

**Comment by EdwardCaulfield** [comment]
Hello Prashant,

Thank you for the reminder.  I’ve not yet had an opportunity to work on the project again since issuing my initial report. If the problem persists (I think there was an upgrade in the meantime), I will use the appropriate tools to report it.

Thank you, however, for your persistence.  After close to 30 years dealing with big companies, it is a rare experience and shows how much the Microsoft culture has improved under the current leadership.  Really a nice thing to see!  Google could learn a lot from you!

Best Regards,

Edward Caulfield
http://360grad.studio/
+41 76 281 1960

If you're not progressing, you're regressing;

This email and any files transmitted with it may contain confidential and/or legally protected information. They are intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender and delete it immediately, considering its dissemination, distribution or copying being strictly prohibited.
