### ISSUE TITLE
"Adding IdentityServer to a Web Application" section

### ISSUE THREAD

**Issue by NandC** [MicrosoftDocs/xamarin-docs#123]
To add IdentityServer, I believe only adding the IdentityServer4.AspNetIdentity NuGet package to Xamarin.Foems app (& configuring) is enough. And no need to add ASP.NET Core web application to the solution??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d805ca5-97c4-23e4-b635-9de16b6d7f78
* Version Independent ID: ec5b37f1-1bd1-c66e-6461-57c104ed543a
* Content: [Authentication and Authorization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/authentication-and-authorization)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@NandC have passed this question on to the author.

**Comment by davidbritch** [comment]
Hi @NandC 

To consume IdentityServer endpoints from a Xamarin.Forms app you don't need to add the IdentityServer4.AspNetIdentity NuGet package to the Xamarin.Forms solution. You just need to add the IdentityModel NuGet package to the Xamarin.Forms solution (in order to serialize/deserialize the required data), and then consume the IdentityServer endpoints through REST API calls. Take a look at the dependencies in the sample app - https://github.com/dotnet-architecture/eShopOnContainers
