### ISSUE TITLE
AVD Location

### ISSUE THREAD

**Issue by dernippel** [MicrosoftDocs/xamarin-docs#125]
Is there a way to set the AVD Location path completely?
My Android SDK is at "D:\Android\android-sdk" and I want to have my Android AVDs at "D:\Android_AVD\".
I already set the environment variable "ANDROID_SDK_HOME" to "D:\Android_AVD". This seems to work half: I'm able to create a new AVD with the device manager but it returns with an error. The AVD is created at "D:\Android_AVD\.android\avd" but it is not listet in the Devices List (it is listed in Visual Studio but could not be started).
I've examined the device manager log:
[18-04-03 06:35:45.90] Executing command: D:\Android\android-sdk\tools\bin\avdmanager.bat "create" "avd" ... seems to be running successfull and uses the environment variable.
But later there is a [18-04-03 06:35:55.53] [ParseManager.WriteIniData] IO error occured while trying to rewrite a file.
on path "C:\Users\<username>\.android\avd\<avdname>.avd\config.ini".

This looks like a hardcoded path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77921f62-3d69-ff6e-57a8-ebe4bffde990
* Version Independent ID: d12d0c6d-5e03-533e-a6cc-fe940ff18206
* Content: [Xamarin Android Device Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/xamarin-device-manager?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/xamarin-device-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/xamarin-device-manager.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @dernippel, according to [Google's documentation](https://developer.android.com/studio/command-line/variables.html#android_emulator_home), it looks like `ANDROID_AVD_HOME` is the environment variable you want to set (we'll include a link to this information so that it is easier to find).

If this doesn't work for you, please open a bug report from within the Xamarin Device Manager according to [these instructions](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/xamarin-device-manager?tabs=vswin#generating-a-bug-report).

Thanks for your feedback!
