### ISSUE TITLE
Thank you. 

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1291]
Hi team, I'm manually (zenhub didn't work) copying this issue here from https://github.com/MicrosoftDocs/xamarin-docs.tr-tr/issues/5 since the user is requesting additional documentation.
from @evereklili
> Thank you. I want to Oracle Document similary. But This systems(documents)
> 
> Belge Ayrıntıları
> 
> ⚠ Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.
> 
>     ID: dac28e18-875a-cb51-a031-717692255d0a
>     Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
>     Content: Xamarin.Android için Android SDK'sını ayarlama - Xamarin
>     Content Source: docs/android/get-started/installation/android-sdk.md
>     Product: xamarin
>     GitHub Login: @conceptdev
>     Microsoft Alias: crdun
>

**Comment by conceptdev** [comment]
I'm not really sure what the feedback is referring to. We are [moving to OpenJDK](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk) (rather than the Oracle Java SDK, going forward), but for now the instructions on [the linked page](https://docs.microsoft.com/xamarin/android/get-started/installation/android-sdk) are our current, recommended approach.
