### ISSUE TITLE
Indicate in which version was introduced a functionality (If necessary)  

### ISSUE THREAD

**Issue by Char0394** [MicrosoftDocs/xamarin-docs#1321]
It would be helpful if we show the version that was introduced a functionality. 
So if the user is in a previous version knows that he has to update to see the feature. 

It is really helpful for example in the case of Xamarin Forms, that a lot of features are being introduced per version.

**Comment by davidbritch** [comment]
Hi @Char0394 

Thanks for your feedback. We took the decision, a while ago, for our docs to reflect the latest release of each platform. This is because, previously, some docs got quite unwieldy due to referencing multiple releases.

However, we can reconsider this decision if it's raised by more people.
