### ISSUE TITLE
AndroidClientHandler on Android 4.4

### ISSUE THREAD

**Issue by UnreachableCode** [MicrosoftDocs/xamarin-docs#1375]
AndroidClientHandler works for me on devices running Android 4.4, but this documentation advises against it. Why is this?

---
#### Document Details

* ID: 969ae3fb-fa08-217b-a62f-105317ea811a
* Version Independent ID: 49deb3eb-6726-62d1-1684-6816d4b4b1cb
* Content: [HttpClient Stack and SSL/TLS Implementation Selector for Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows)
* Content Source: [docs/android/app-fundamentals/http-stack.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/http-stack.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
I don't think the intention is to advise _against_ `AndroidClientHandler` on Android 4.4, just that you may not be getting full TLS 1.2 support on that version of Android.

As [discussed in the doc](https://docs.microsoft.com/xamarin/android/app-fundamentals/http-stack?tabs=windows#choosing-a-handler), `HttpClientHandler` can support TLS 1.2 on older versions of Android using **BoringSSL**, which is why it's advised for versions older than Android 5.0.

You should choose the handler, and minimum version of Android that your app supports, based on your desired level of security.
