### ISSUE TITLE
No pure code examples

### ISSUE THREAD

**Issue by donaldnp** [MicrosoftDocs/xamarin-docs#1376]
I can't see a single C#-only example anywhere here. I initially landed on the corresponding page in the XAML "tree", and found an issue which directed people to this tree to find how to do it in just code... and yet here also is a page covered in XAML! Where can one find how to do data-binding in JUST C# code?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd1063-e094-1bda-e2ec-f63a0136523d
* Version Independent ID: 6e25673a-374a-2f05-f610-984d22e52053
* Content: [Xamarin.Forms Basic Bindings - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/data-binding/basic-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/basic-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/basic-bindings.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @donaldnp it's true that we focus on XAML for data-binding since that is the focus of most of our customers. However, the [first section](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/basic-bindings#bindings-with-a-binding-context) of the page you referenced shows data binding in C# code:

```csharp
label.BindingContext = slider;
label.SetBinding(Label.RotationProperty, "Value");
```

The [second section](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/basic-bindings#bindings-without-a-binding-context) shows a slightly different syntax:

```csharp
label.SetBinding(Label.ScaleProperty, new Binding("Value", source: slider));
```

Don't be mislead by the XAML layout in these examples, you could just as easily create the ContentPage, StackLayout, Label, and Slider in C# -- the UI declaration is not the key part of these explanations, it's the `SetBinding` method.
