### ISSUE TITLE
Preserve attribute

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/xamarin-docs#1398]
The documentation above tells you to use the `Preserve` attribute, but this attribute is in the Internals namespace, and I'm assuming we shouldn't be using that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a849344-bfe7-89eb-3949-10591484a2cf
* Version Independent ID: 8be4b6ea-3cd8-8d74-58db-b07dcdf78ab6
* Content: [XAML Custom Namespace Schemas in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/custom-namespace-schemas)
* Content Source: [docs/xamarin-forms/xaml/custom-namespace-schemas.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/custom-namespace-schemas.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by dotMorten** [comment]
cc @davidortinau

**Comment by davidbritch** [comment]
Awaiting the result of an internal discussion before deciding on a course of action.

**Comment by davidbritch** [comment]
Hi @dotMorten 

The `Preserve` attribute in the Internals namespace is going to be marked obsolete, and a new version of it will be created in the Xamarin.Forms namespace for people to use (see the issue at https://github.com/xamarin/Xamarin.Forms/issues/5244).

I've created an issue in our backlog to update the doc when this happens, so will close the issue here now.

**Comment by dotMorten** [comment]
Awesome. Thank you. It might be worth adding to the doc that it can also be any home-made Preserve Attribute for when you need it in libs that doesn't reference Xamarin.Forms

**Comment by davidbritch** [comment]
Good suggestion. Linking to this issue from our backlog, so I don't forget.
