### ISSUE TITLE
What behaviour is? I am not able to see defination

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#1432]
I don't know I am wrong or right. But I am not able to see basic definition of behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de196cde-8c57-8c92-4495-fcfa066682f9
* Version Independent ID: 50986b5c-9e22-fd23-aed7-2d3b15ae0dbf
* Content: [Xamarin.Forms Behaviors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/creating.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @arvindrajachourasiya 

Try downloading the sample from the link at the top of the page, and take it from there.

**Comment by arvindrajachourasiya** [comment]
@davidbritch - I am not asking about sample.  I am just asking definition of behavior. 

**Given definition in docs**: Xamarin.Forms behaviors are created by deriving from the Behavior or Behavior<T> class. This article demonstrates how to create and consume Xamarin.Forms behaviors.

Here you are telling about how Behavior **creating**. But not telling what Behavior is.

Thank you :)

**Comment by davidbritch** [comment]
@arvindrajachourasiya 

You've started reading the behaviors guide at part 3 of it. I recommend part 1 - [Introduction](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/behaviors/introduction).

**Comment by mshwf** [comment]
@arvindrajachourasiya I have similar confusion about behaviors due to the behavior as defined [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/attached) as attached property and [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating) as deriving from `Behavior<T>` class, the only common thing between them is the capability of enriching the view's _behavior_, typically by subscribing to some events. Any reusable code that could do this is a behavior- I think!
