### ISSUE TITLE
Why choose the base class as render in UWP？

### ISSUE THREAD

**Issue by yelinzh** [MicrosoftDocs/xamarin-docs#1446]
Grid is rendered as FrameworkElement in UWP.Why choose the base class as render in UWP rather than an additional class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfee594b-8ecc-0d4d-9384-e4afe792b3dd
* Version Independent ID: 9957d9e1-1ebc-aadb-90bb-5e80b595bade
* Content: [Renderer Base Classes and Native Controls - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers#layouts)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @yelinzh 

All Xamarin.Forms controls (`Grid`, `ListView` etc.) map onto a native type in the specific platform (in this case UWP). You might think that a Xamarin.Forms `Grid` should map to a UWP `Grid`, but in Xamarin.Forms layout is handled by Xamarin.Forms core classes, rather than relying on native platform classes, so that there's consistent layout across the different platforms. Therefore, each Xamarin.Forms layout class (`StackLayout`, `Grid` etc.) maps to a platform UI base type (`UIView` on iOS, `View` on Android, `FrameworkElement` on UWP). This permits Xamarin.Forms to create and control the required layout.
