### ISSUE TITLE
Missing x namespace attributes in table

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#1478]
Previous sections in this topic mention the following attributes that do not appear in table
x:static
x:null
x:type
x:array
x:reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb234b9-b1c1-e43e-6015-466de8ff0ce3
* Version Independent ID: e66ed6aa-c7fa-8ead-e828-73c17a15320c
* Content: [XAML Namespaces in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/namespaces)
* Content Source: [docs/xamarin-forms/xaml/namespaces.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/namespaces.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

Thanks for the feedback. The attributes you've listed aren't in the table because technically they aren't attributes. They are markup extensions (see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/markup-extensions/consuming). However, I've added a note/link to the doc to that effect.
