### ISSUE TITLE
Please explain how static bindable props are associated with actual instance.

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#1479]
Hi,

Given the bindable props are static to class plz explain how the prop values map to correct class instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b054a909-6f7f-0b32-5059-eb5c8a9b366b
* Version Independent ID: 723af07b-8f4e-ebe3-a520-99cdcf5efc5a
* Content: [Bindable Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties)
* Content Source: [docs/xamarin-forms/xaml/bindable-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/bindable-properties.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

The docs don't generally go into the *how*, because this is an internal implementation detail that may change over time. If you're interested in the *how*, all I can do is recommend you take a look at the Xamarin.Forms [source code](https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.Core).
