### ISSUE TITLE
SqliteConnection does not exist in sqlite-net-pcl

### ISSUE THREAD

**Issue by DianaKoenraadt** [MicrosoftDocs/xamarin-docs#1528]
It's not possible to invoke SqliteConnection.SetConfig(SQLiteConfig.Serialized);

No, not even when the lowercase/uppercase letters are correct. The SQLiteConnection.SetConfig method does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3059afc-7e56-a214-0463-c87bd9b5ca21
* Version Independent ID: a879cca8-1d5e-bab9-1b2d-32a9ece48022
* Content: [Using SQLite.NET with Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/data/using-sqlite-orm#feedback)
* Content Source: [docs/ios/data-cloud/data/using-sqlite-orm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/data-cloud/data/using-sqlite-orm.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks for your question @DianaKoenraadt - the code is capitalized correctly, but the page isn't clear that it's referring to the `Mono.Data.Sqlite` namespace because it's setting the configuration directly on the SQLite 'engine'. We'll update the documentation to make this clear, but you can solve it with either
`using Mono.Data.Sqlite;` or `Mono.Data.Sqlite.SqliteConnection.SetConfig(SQLiteConfig.Serialized);`

Alternatively, right-click on the `SqliteConnection` classname when it has a red-squiggly underline and the **Quick Fix** content menu should offer both these options to fix it.
