### ISSUE TITLE
Why do we need to define get and set methods with attached properties?

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#1553]
I was able to run the the code in the class `NumericValidationBehavior` [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating#consuming-a-xamarinforms-behavior-with-a-style) without defining `GetAttachBehavior` and `SetAttachBehavior`, so why it's always required in every attached property to define getter and setter methods?

here's the complete class I have:
```csharp
public class NumericValidationBehavior : Behavior<Entry>
    {
        public static readonly BindableProperty AttachBehaviorProperty =
            BindableProperty.CreateAttached("AttachBehavior", typeof(bool), typeof(NumericValidationBehavior), false, propertyChanged: OnAttachBehaviorChanged);

        private static void OnAttachBehaviorChanged(BindableObject bindable, object oldValue, object newValue)
        {
            if (!(bindable is Entry entry)) return;
            bool attachBehavior = (bool)newValue;
            if (attachBehavior)
            {
                entry.Behaviors.Add(new NumericValidationBehavior());
            }
            else
            {
                var toRemove = entry.Behaviors.FirstOrDefault(b => b is NumericValidationBehavior);
                if (toRemove != null)
                {
                    entry.Behaviors.Remove(toRemove);
                }
            }
        }

        //public static bool GetAttachBehavior(BindableObject view)
        //{
        //    return (bool)view.GetValue(AttachBehaviorProperty);
        //}
        //public static void SetAttachBehavior(BindableObject view, bool value)
        //{
        //    view.SetValue(AttachBehaviorProperty, value);
        //}

        protected override void OnAttachedTo(Entry bindable)
        {
            base.OnAttachedTo(bindable);
            bindable.TextChanged += Entry_TextChanged;
        }

        private void Entry_TextChanged(object sender, TextChangedEventArgs e)
        {
            var isNum = double.TryParse(e.NewTextValue, out double result);
            ((Entry)sender).TextColor = isNum ? Color.Default : Color.Red;
        }

        protected override void OnDetachingFrom(Entry bindable)
        {
            base.OnDetachingFrom(bindable);
            bindable.TextChanged -= Entry_TextChanged;
        }
    }
```

in App.xaml:
```xml
<Style TargetType="Entry">
      <Setter Property="beh:NumericValidationBehavior.AttachBehavior" Value="True"/>
</Style>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de196cde-8c57-8c92-4495-fcfa066682f9
* Version Independent ID: 50986b5c-9e22-fd23-aed7-2d3b15ae0dbf
* Content: [Create Xamarin.Forms behaviors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating#consuming-a-xamarinforms-behavior-with-a-style)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mshwf 

Ever since attached properties were introduced in WPF, they were typically implemented as a bindable property, with get and set accessors. WPF required the get/set accessors, otherwise the property system would be unable to use the attached property. In addition, it was required for required for data binding on the property to work in the Visual Studio designer, and in Expression Blend.

Xamarin.Forms adopts the WPF attached properties pattern in order support consuming the attached properties through both XAML and C#. When consuming an attached property through XAML, the `BindableProperty` version of the attached property is consumed, and it bypasses the get/set accessors, instead calling the `GetValue`/`SetValue` methods from the `BindadbleObject` class.

When consuming an attached property through C#, the attached property getters/setters are consumed, and so the property system can interact with the attached property.

Hope this helps!

**Comment by mshwf** [comment]
Interesting!
Never noticed such a difference between the xaml and the C# version in Xamarin. Thanks for clarifying!
