### ISSUE TITLE
Now that VS 2019 Mac has shipped, is this still relevant?

### ISSUE THREAD

**Issue by paulelong** [MicrosoftDocs/xamarin-docs#1576]
I'm unable to Pair from VS2019 on my PC to my Mac VS2019 version 8.0.1.  But reading this article, I wonder if the steps are still relevant and maybe the pairing is still in beta?  Can the article be clarified, or removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d4dcc7c-5d4b-e75d-2295-e80909b5dafc
* Version Independent ID: 693733be-56b7-27f9-dd24-af7c458170c5
* Content: [Connecting Visual Studio 2019 Previews on Windows and macOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/2019-preview#feedback)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/2019-preview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/2019-preview.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks for your feedback @paulelong. You should be able to pair Visual Studio 2019 from PC to Mac. You're right about this page being intended for the Preview builds - I'll check with the team whether we need to remove this page.

As far as I'm aware, the pairing should work with the stable builds of Visual Studio 2019 released last week. If you continue to experience issues, please [report them in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019), since that will include useful version and system information that can help to diagnose.

**Comment by conceptdev** [comment]
I've confirmed the article is not relevant to the released Visual Studio 2019, it will be removed (and redirected to the main pairing page). As I mentioned above, if you continue to encounter problems please report them in Visual Studio.
