### ISSUE TITLE
MVVM Example?

### ISSUE THREAD

**Issue by rdurrance** [MicrosoftDocs/xamarin-docs#1628]
Since it seems that everything is moving to MVVM, can you update this to include a ViewModel? This is an excellent tutorial but anything more advanced almost requires that you use MVVM. If you go into the forums, all of the Xamarin people are saying "Why are you using Item source in the code behind, put it in the model" even when others are asking questions that are directly related to the example in this tutorial. Also, taking into consideration that most people looking at these tutorials and examples are just starting out, shouldn't they be learning the recommended way to databind?  At the very least, you could provide an example with a ViewModel with the clarification that this is one way, and using the code-behind is another. Just a thought.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database?pivots=windows)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your feedback @rdurrance. This is a difficult question, with no right answer, and we constantly struggle to find the right balance. One way we address this is by providing additional learning options like Xamarin University (soon moving to Microsoft Learn).

This example is intended to be as simple as possible - this might be the first application a developer creates with Xamarin. More complex stuff like app architecture and data binding can be learned later, rather than cramming lots of theory into the first ever app. While these concepts seem simply to experienced developers, every little 'extra' thing in a beginner tutorial can be a source of confusion or error. Knowing about MVVM is no use if they abandon the product before they finished their first sample app!

The [deep dive](https://docs.microsoft.com/xamarin/get-started/quickstarts/deepdive) at the end of the get-started series introduces these topics and links off to our more detailed documentation.
