### ISSUE TITLE
Incorrect available version 

### ISSUE THREAD

**Issue by kdawg1406** [MicrosoftDocs/xamarin-docs#1647]
Docs state:  CollectionView is available in the Xamarin.Forms 4.0 pre-releases

I'm using XF 3.6 and CollectionView is in the release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9de402a5-a78c-3cfe-f9b1-443a3401574b
* Version Independent ID: 4488127d-8fe9-eef6-c665-106b493f93fd
* Content: [Xamarin.Forms CollectionView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @kdawg1406, due to a packaging decision by the team, a number of Xamarin.Forms 4.0 Preview features have classes that appear in the 3.6 NuGet. To properly use these features, however, requires the feature flag code `Forms.SetFlags("CollectionView_Experimental");` be called.

Until Xamarin.Forms 4.0 is stable, it's not recommended to use those preview features in your production applications. You can read about Xamarin.Forms availability on the [roadmap](https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap).

**Comment by kdawg1406** [comment]
@conceptdev thank you, understand adding SetFlags.  FYI:  CollectionView is in the Toolbox.  

Thank you for a very fast reply.  Maybe add your text as a note in the topic?

Best to you,

Karl

**Comment by conceptdev** [comment]
Yes, the preview controls appearing in the toolbox is an unfortunate side-effect of the _feature flags_ approach, and very confusing. Thanks for your feedback - passing it on to the team.

**Comment by kdawg1406** [comment]
I'm actually glad it's available in 3,6.  With the caveat for testing and evaluating only.  If they updated the docs, with your information, I think its a win-win.  

But... if they drag from the toolbox, it won't work without reading your information in the docs and using SetFlags.  Could cause a pain point for a customer.

Maybe there is a way to allow the developer to opt-in to an experimental feature and then it goes in the ToolBox?

Best to you,

Karl

**Comment by conceptdev** [comment]
Definitely a pain-point. More thought/planning is required before we use this feature-flag strategy again in future!
