### ISSUE TITLE
Issues with this documentation...

### ISSUE THREAD

**Issue by justintoth** [MicrosoftDocs/xamarin-docs#168]
There are a few issues with this documentation...
1. The instructions show a Components folder in solution explorer where you can check if it already has nuget packages. However, Visual Studio for Mac has removed the Components folder, so this step cannot be followed.
2. After removing all XamarinComponentReference nodes from my project files, closing and reopening my solution in Visual Studio for Mac still gives the super annoying warning message about components. So these directions don't work at all and I'm stuck seeing this warning message constantly.

P.S. Whoever made the decision to show this warning message EVERY SINGLE TIME the solution is opened is not my friend. Putting in smarter logic like once/week would've been more reasonable, if the goal was to be annoying then you achieved it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e0d3ab-3d52-7966-34ac-f04236fe9d20
* Version Independent ID: cc8fb372-39b4-7ec1-5911-1bfbed905daf
* Content: [Updating component references to NuGet - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/component-nuget?tabs=vsmac)
* Content Source: [docs/cross-platform/troubleshooting/component-nuget.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/troubleshooting/component-nuget.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
@justintoth I've made some edits to the page to clarify.

Regarding still seeing the error messages, I've just tested it and was able to resolve by following the instructions. You can submit issues (if it continues to occur after you've removed the nodes) and product feedback at https://developercommunity.visualstudio.com/ (choose the relevant IDE/platform tab at the top).

**Comment by justintoth** [comment]
You put a warning that the instructions only apply to older versions of Visual Studio for Mac, but don't provide instructions for the latest version of Visual Studio for Mac. Removing the XamarinComponentReference nodes from the proj files clearly isn't enough, as I'm still getting the warning. It seems like you'd want the documentation to be with the latest version, adding the warning isn't the right update to make to the documentation...

**Comment by conceptdev** [comment]
The only instructions that work in the latest IDE are at the [top of the page](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/component-nuget?tabs=vsmac#manually-removing-component-references) - select the correct tab for your platform. I've left older instructions below, because many people do not upgrade immediately after a release, and may find them useful still.

I've tested them again today and the steps work for me. I'm sorry you're having issues with it - I'd strongly encourage you to raise an issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html), especially if you can include the solution that is failing, so that it can be investigated and resolved.

**Comment by blatzblaster** [comment]
How are we to determine which Components contain NuGet packages without having the Components UI?

**Comment by joehanna** [comment]
How do I get replacements for paid components (without penalty) that you are making obsolete all of sudden?

**Comment by conceptdev** [comment]
@joehanna we have been messaging this to component vendors for a while now (even before the [Nov 2017 announcement](https://blog.xamarin.com/hello-nuget-new-home-xamarin-components/)), and encouraging them to find alternate distribution mechanisms. I am not sure of the policies of any specific vendor, but I'd encourage you to reach out to them directly.

For product feedback, you can raise an issue on the [Developer Community site](https://developercommunity.visualstudio.com/spaces/41/index.html).

**Comment by joehanna** [comment]
Thanks for your response @conceptdev. My point is I have already paid Xamarin for the component and now I am *forced* to buy it again from the vendor.  This is unfair.

**Comment by Redth** [comment]
@joehanna You can still manually download the component from the store which you own and extract the .xam file (it's really just a .zip file) and reference the assemblies from the component directly.  There's nothing preventing you from keeping a copy of the component locally and using it forever this way.

Unfortunately, we can't really speak to the practices of this vendor - most vendors we've worked with have been happy to move existing customers over to new distribution mechanisms.  Is it possible the vendor is requesting you to pay since it's a newer version of the component than you originally purchased on the store?

**Comment by joehanna** [comment]
Thanks @Redth.  Manually downloading the component works for me.  

I tried reaching out to the vendor (Appracatappra) but was ignored. 

Thanks for your help.
