### ISSUE TITLE
Broken link to sample project

### ISSUE THREAD

**Issue by AChorostian** [MicrosoftDocs/xamarin-docs#1694]
As in title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b9e0c6-7539-cbe0-81a3-0342f1fe9907
* Version Independent ID: 742a82e9-8cdc-4df7-5f41-5c37d1311556
* Content: [Checking Device Orientation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/device-orientation#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/device-orientation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/device-orientation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by AChorostian** [comment]
(On the top of the page, just under the title of this article)

**Comment by davidbritch** [comment]
Hi @AChorostian 

This is due to a backend change that requires that our sample links use correct casing. Some of our links are all lowercase, which is no longer permitted. So the quick fix is to capitalise the link as required. 

In the meantime, I'm going to identify all the links that need updating, and update them.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later.
