### ISSUE TITLE
download the sample link at top dead

### ISSUE THREAD

**Issue by user135711** [MicrosoftDocs/xamarin-docs#1698]
Another d.l.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06aff09-e5dd-9bba-d158-f3b61984d735
* Version Independent ID: 72c8ef2a-01f3-aee4-9a84-11995565b2d3
* Content: [Reusable EventToCommandBehavior - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @user135711 

This is due to a backend change that requires that our sample links use correct casing. Some of our links are all lowercase, which is no longer permitted. So the quick fix is to capitalise the link as required. 

In the meantime, I'm going to identify all the links that need updating, and update them.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later.
