### ISSUE TITLE
Sample link is bad

### ISSUE THREAD

**Issue by davidortinau** [MicrosoftDocs/xamarin-docs#1701]
Related Links sample url is invalid or not properly redirecting to the sample. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36e7942-65b6-9877-aafd-5f1b1291d37d
* Version Independent ID: 77a599a6-43f2-068f-95ad-0a92ca2b4bca
* Content: [Customizing a ContentPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @davidortinau 

This is due to a backend change that requires that our sample links use correct casing. Some of our links are all lowercase, which is no longer permitted. So the quick fix is to capitalise the link as required. 

In the meantime, I'm going to identify all the links that need updating, and update them.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later.
