### ISSUE TITLE
Flyout with Tabs and no DataTemplate

### ISSUE THREAD

**Issue by davidortinau** [MicrosoftDocs/xamarin-docs#1712]
The first flyout example shows FlyoutItem &gt; Tab &gt; ShellContent. I'm concerned this is bad practice.

1. Why use Tab if all you want are flyout items? Let's omit the Tab. 
2. Why not use DataTemplate on the ShellContent? These pages will be created automatically, slowing load, and not benefit from the templating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a303fbe7-5786-651e-e730-90efb1796e72
* Version Independent ID: 6a6a96eb-7563-8b4f-1272-1eb7bd221fb7
* Content: [Xamarin.Forms Shell Flyout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/flyout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/flyout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @davidortinau 

In answer to your questions:

1. It's worse than that. Why use FlyoutItem when all you want are flyout items? You don't have to. The docs are intended to be read in order, as a guide. An earlier doc explains the hierarchy of Shell objects (ShellContent being a child of Tab etc.). At this stage in the guide, this hierarchy is still adhered to, in order to reduce the readers cognitive load. However, within the same H2 section, the implicit conversion operators are explained, and a reduced code example shown.
2. Shell has a *huge* cognitive load. Good pedagogy dictates that learning material should attempt to lighten this load. Rather than introduce every new concept simultaneously, the docs attempt to reduce the cognitive load using familiar concepts where possible (in this case, displaying a page). However, throughout the Shell docs, whenever a ShellContent doesn't use templating, there's a note within the same section (with a link) pointing out that templating is a better approach.
