### ISSUE TITLE
The image

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1730]
Not working
The image is called splash_logo.png, not splash (how you call it in the splash_screen.xaml)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen#feedback)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by dinobu** [comment]
Now working, I get error
No resource found that matches the given name (at 'android:windowBackground' with value '@drawable/splash_screen').	MyApp.App.Droid	C:\source\MyApp.App.Droid\Resources\values	C:\source\MyApp.App.Droid\Resources\values\styles.xml

**Comment by dinobu** [comment]
In addition, if the image is to take whole screen, this will stretch image causing it to not look good

**Comment by dinobu** [comment]
... also the image must be added as AndroidResource

**Comment by farr64** [comment]
Actually, I wasted a lot of time because I had included the **.png** extension as an integral part of the image file's name.

 I had tried everything that I found on myriad forums and nothing helped: That annoying and absurd error message would not disappear: No resource found that matches the given name.

In desperation, given that the situation was desperate, I decided to follow the tutorial without deviating at all (including "**excluding** the .png extension" ;-) and bingo! Everything worked and I now (after much wasted effort) have a splash screen on Android. It still doesn't scale nicely, as is the case on iOS, but that's another hurdle to be overcome after some sleep.

What a pain.

Still: Thanks very much, Microsoft folks, because I know that you are working hard and I appreciate your efforts. Given yor passion and focus, you'll get it right.
