### ISSUE TITLE
Build your first Xamarin.Forms App

### ISSUE THREAD

**Issue by dovberman** [MicrosoftDocs/xamarin-docs#1737]
I have tried to use this article for 5 days. It does not work for me. Steps are missing. For instance, where is the  item that shows &gt;Samsung SM-N95OU1 (Android 8.0 - API26) in a dropdown list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows#feedback)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
The article only discusses the Android emulator - if you see **Samsung** in your device list it's likely because you have an Android phone plugged into your computer.

The [installing Xamarin](https://docs.microsoft.com/xamarin/get-started/installation/) and [Android emulator setup](https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/) documentation might be useful for you.

**Comment by dovberman** [comment]
This is very helpful.

 

Thanks,

 

David Martin
