### ISSUE TITLE
Editor keyboard flags not define warning

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#1784]
&lt;Keyboard x:FactoryMethod="Create"&gt;
gives warning....
"The keyboard is not usable as an object element because  it is not public or......."
Explain this . example works fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8881d8f1-1d94-e090-e709-aca80b644a78
* Version Independent ID: 298aeed6-5e3e-f053-10f0-66d1061b4b2e
* Content: [Xamarin.Forms Editor - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/editor)
* Content Source: [docs/xamarin-forms/user-interface/text/editor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/editor.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @shalinasanga 

There can be many reasons for this occurring. But as the sample works for you, I can only suggest that the problem lies within your own solution somewhere. You should check that you're using the same version of Xamarin.Forms in each project, and also delete your bin/obj folders and try again.
