### ISSUE TITLE
UI freeze on internet connection

### ISSUE THREAD

**Issue by nakulashok** [MicrosoftDocs/xamarin-docs#1818]
UI is freezing while connecting to network.

**Reproducing steps**
1. Go to some pages where there are UI controls like picker.
2. Turn on the wifi so that wifi auto connects to some network with internet access.
3. Open and close the picker repeatedly while the wifi is connecting to the network.
4. UI freezes for a second.

**Device Information**
1. **OS** : Android oreo 8.1
2. **Phone** : Honor 8x

**Comment by conceptdev** [comment]
@nakulashok bugs and issues with Visual Studio should be reported directly in the IDE, using the **Help > Report a problem** menu item.

This issues list is specifically for the documentation. Reporting directly in Visual Studio will provide more information to the team for debugging. Thanks.

**Comment by nakulashok** [comment]
@conceptdev this is not issue related to the IDE. 
When I install the app and test it in real device I am facing this issue.

**Comment by conceptdev** [comment]
Nevertheless bugs should be reported via **Help > Report a problem**. If you believe the issue is with Xamarin.Forms, you can use the open-source issues list https://github.com/xamarin/xamarin.forms/issues

This documentation site is not a support forum, for community help visit [stackoverflow.com](https://stackoverflow.com/questions/tagged/xamarin).
