### ISSUE TITLE
RelativeLayout not working properly like in the tutorial

### ISSUE THREAD

**Issue by ducanhn** [MicrosoftDocs/xamarin-docs#1826]
I try following the tutorial. If i switch to LinearLayout then it work fine. But RelativeLayout is not working properly. I use VS 2019. 
Here's the link to the screenshot of my issue :
https://framapic.org/PyW0NmoZZrDA/YAWBL3y7v2gJ.JPG
The tutorial :
https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows

**Comment by conceptdev** [comment]
The tutorial is written for `<LinearLayout>` see the **Tip** in this [section](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows#create-a-layout). 

Please see the [`RelativeLayout` docs](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/relative-layout) for more information. 

If you continue to have issues, try to test on a real device, to see if the issue is with the Visual Studio designer or not. Use **Help > Report an issue** menu in Visual Studio to create a report for the engineering team.
