### ISSUE TITLE
This page should be split into multiple pages

### ISSUE THREAD

**Issue by thekeviv** [MicrosoftDocs/xamarin-docs#1862]
This is really big and should be created into a nested list as is the parent of this article. I looked at 46 minutes to read and I was like no. This has really useful stuff which deserves separation into sub pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8860356f-6193-b6bf-8628-7d7c9800200f
* Version Independent ID: d5e4a416-67e2-b276-c534-65d70ca3cc1c
* Content: [Working With JNI - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/java-integration/working-with-jni#feedback)
* Content Source: [docs/android/platform/java-integration/working-with-jni.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/java-integration/working-with-jni.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @thekeviv. It is sometimes difficult for us to pick the best way to package content - some readers prefer smaller pages to scan, others prefer a single long page that they can search through, or print/PDF as a reference. We try to to understand how our customers are likely to use each type of content, and display it accordingly.

In this case, a single long document was chosen because smaller chunks wouldn't necessarily make sense as standalone docs, and while the reading time may seem onerous at first, realistically you probably need to read the whole thing to be successful with JNI. I hope you still find the content useful.
