### ISSUE TITLE
Two Errors?

### ISSUE THREAD

**Issue by jzelis** [MicrosoftDocs/xamarin-docs#1865]
I ran into two errors while trying to run this demo. I created the project using VS 2019 professional. 
Steps to duplicate. 
Create project utilizing the mobile app (xamarin forms) template from the Project Type MOBILE
Cut and paste the code provided. 
Two errors (Types) show in design time:
1) Missing context for xaml controls "listView", "nameEntry", etc....
2) Duplicate Xaml Compilation Attribute

the second error appears to be caused by the template creating AssemblyInfo.cs with the attribute....
don't know if removal causes the the app to fail or not because I cant get the code to recognize the missing context for the xaml.

I'm new to Xamarin so this is quite frustrating when the simplistic example provided doesn't compile.

Any help would be appreciated.

-Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d277d164-ac67-d097-dba9-3be6f3c2534f
* Version Independent ID: 30c44243-738f-b964-81be-deb28928843f
* Content: [Xamarin.Forms Local Database Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/local-database/index?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/local-database/index.yml](https://github.com/MicrosoftDocs/xamarin-docs-pr/blob/live/docs/get-started/tutorials/local-database/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jzelis 

Thanks for the feedback, and sorry you've encountered these issues.

Your second error (duplication XamlCompilation attribute) is due to a change in the Xamarin templates in Visual Studio, that was made since this content was published. I've updated all of our get started content to reflect these updates, in a PR that will hopefully go live soon. If you want a quick solution to this issue, find the `XamlCompilation` attribute in **App.xaml.cs** and remove it.

I worked through the tutorial in VS2019 and had no problems making it build (bearing in mind my previous paragraph). A quick search reveals that others have had similar issues in the past, generally. I recommend trying the solutions listed at https://forums.xamarin.com/discussion/61431/xaml-control-does-not-exist-in-the-current-context

**Comment by jzelis** [comment]
Thanks David. I figured as much on the duplication attribute and thanks for the heads up on the other problem. I will look into it. It's great that you take the time not only to create these examples but also follow up as MS progresses their templates and scaffolding. Keep up the good work.
