### ISSUE TITLE
Question about the old API links

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#1937]
There are still quite a few API links pointing to _developer.xamarin.com/api/etc_. Right now, most of them work just fine (for the APIs that have been migrated over to Microsoft Docs) but I was wondering if I should update the links anyway whenever I edit an article that has them? Or, do you have an internal plan for batch updating them at some point in the future?

I'm sure that the xamarin.com site with proper redirections will be around for a long time but still, this would save an unnecessary redirection.

**Comment by conceptdev** [comment]
We definitely plan to do a bulk update, but thanks for asking. 

A little bit of history - we moved each platform API docs over separately, Xamarin.Forms was a while ago, but Android and iOS only happened very recently (past month or so). 

When we moved Xamarin.Forms, we did update all the links. If you look at the source, you'll notice that they are no longer "real links", but have the form `[some api](xref:Xamarin.Forms.SomeAPI)` -- `xref:` is a special feature of docs.microsoft.com, where the markdown parser actually validates the namespace/type/member/property against the API reference and generates a valid link at rendering time. This is great for validation (we get warnings if there is a typo or invalid entry) and it will enable cool features in the future.

The batch update didn't happen for iOS or Android links just because of time constraints, but it is planned!

Unfortunately it is difficult for customers to use the `xref:` syntax because there is no CI or validation on your PRs. 

For now, I would suggest just leaving any working redirect links as-is. However if you find a broken link or redirect, please do flag it for us, or submit a PR with a suggested change. We appreciate your contributions!

**Comment by HankiDesign** [comment]
Thanks for the detailed explanation @conceptdev! I wasn't aware of the `xref:` feature before but it absolutely makes sense, cool stuff.
