### ISSUE TITLE
Error in sample code snippet "A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'IList'"

### ISSUE THREAD

**Issue by andriysavin** [MicrosoftDocs/xamarin-docs#1947]
The last code snippet gives me compilation 3 errors like "XLS0503 A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'IList'".  The docs say "Every ShellContent object is a child of a Tab object". However, in the code snippet the last three ShellContent elements are children of the FlyoutItem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b70380-164f-2b1d-7480-bd9a92381c7d
* Version Independent ID: 504defb4-61ea-add0-1ad4-04f86fac2d2e
* Content: [Create a Xamarin.Forms Shell Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/create#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/create.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/create.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @andriysavin 

These are intellisense errors rather than compiler errors. While every ShellContent object is a child of a Tab object, there are implicit conversion operators that allow you to miss out Tab objects from your source. So when a ShellContent is a child of a FlyoutItem, the ShellContent is wrapped in a Tab object

If you take a look at [this issue](https://github.com/xamarin/Xamarin.Forms/issues/3864), you'll see that the intellisense errors will be fixed in VS 2019 16.3 Preview.

**Comment by andriysavin** [comment]
@davidbritch Oh, I didn't know about that trick with conversion in such context, thank you for explaining. Is that documented somehow somewhere? Because while this is common and obvious in C#, it might be unexpected in XAML unless clearly documented.

**Comment by davidbritch** [comment]
@andriysavin 

It's all mentioned in the docs. It's worth reading them all because the example in the "Create a Shell application" page is optimised for understanding, rather than performance. If you work through the rest of the docs it simplifies the code, while using lazy loading for pages (better perf).

**Comment by andriysavin** [comment]
@davidbritch thank you!
