### ISSUE TITLE
No UWP images

### ISSUE THREAD

**Issue by robv8r** [MicrosoftDocs/xamarin-docs#1963]
While iOS and Android are fine platforms, we write applications for a Microsoft Operating System named Windows.  It would be very nice if UWP examples were also shown.  (Unless Xamarin is only for phones.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c3eb3c8-5769-0b04-2b54-c52b1b98b4be
* Version Independent ID: c150f5fe-a0d8-b6ba-8234-ea219ba9f653
* Content: [Xamarin.Forms Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/)
* Content Source: [docs/xamarin-forms/user-interface/picker/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/picker/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @robv8r 

For this issue you're best discussing your concerns with @pauldipietro, one of the Xamarin.Forms PMs.

**Comment by robv8r** [comment]
I'm a bit confused.  I thought this was for documentation feedback.  This documentation is incomplete.  It ignores Microsoft's primary platform.  Suggesting I take it up with a Project Manager is a bit extreme.

If this is how Microsoft treats people who offer feedback, why bother?

**Comment by robv8r** [comment]
@pauldipietro, I provided documentation feedback and was referred to you by @davidbritch.

My question regarded the lack of UWP screenshots in Xamarin.Forms documentation.  Are you the correct person to address this?

Also, why was this issue closed?

**Comment by conceptdev** [comment]
@robv8r thanks for your feedback. In fact, the screenshots on this page (and most others) historically included Windows Phone (Xamarin.Forms first supported Windows Phone 7 Silverlight!). You can see this in the [GitHub history](https://github.com/MicrosoftDocs/xamarin-docs/commits/live/docs/xamarin-forms/user-interface/picker/images/picker-initial-large.png); however we removed those screenshots as they were confusing to people since Windows Phones are no longer available.

Like all teams, we are resource constrained, and forced to choose where to focus our efforts. In that regard, we follow the lead of the PM & engineering teams, so our focus is on creating new content for Xamarin.Forms 4.x - which includes many Android- & iOS-only features like Shell and CollectionView. 

Where we have chosen not to supply 'preview' images of what UWP controls look like, for now I can only refer you to the [UWP documentation](https://docs.microsoft.com/windows/uwp/), or to download and run our samples (where we still endeavor to support UWP as much as possible).

We'll keep your feedback in mind as we update content in the future. I'm sure the PM team would still be interested in your feedback on your usage of the UWP features of Xamarin.Forms.

**Comment by robv8r** [comment]
@conceptdev - You're releasing features that are for Android and iOS ONLY?  You're not even going to port the Shell to UWP?  That really worries me.  It suggests that Xamarin.Forms remains a "mobile development platform" instead of a "cross platform development tool."

If you're referring me to UWP documentation, I'm guessing that the Xamarin Team is giving up on UWP (or simply ignoring people who attempt to use Xamarin.Forms with UWP).

**Comment by conceptdev** [comment]
@robv8r as was mentioned above, that conversation is best had with the PMs and engineers that are building Xamarin.Forms. You can view the [roadmap](https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap) and [raise issues](https://github.com/xamarin/xamarin.forms/issues) on GitHub with your questions or concerns.

**Comment by robv8r** [comment]
@conceptdev This is still about documentation.  It is incomplete.  This is a valid issue.  Claiming the documentation IS complete suggests UWP doesn't matter to Xamarin.
