### ISSUE TITLE
A lot of Chinese content from machine translation, how to learn xamarin documentation?

### ISSUE THREAD

**Issue by kssoftwangwg** [MicrosoftDocs/xamarin-docs#2014]
The documents are not friendly to Chinese, and some documents are translated by machine, which makes the knowledge points difficult to understand。Can use Microsoft MVPs to translate documents？(文档对中文支持不友好，部分文档来机器翻译，导致知识点无法理解,能不能投入些 MVP 翻译文档？)

**Comment by conceptdev** [comment]
Thanks for your feedback @kssoftwangwg - while we try to provide human translation for as much content as we can (such as Get Started and Deployment information), because of the volume of documentation some of the work is done by machine.

We are always looking to improve the quality of our translations. I will mention your suggestion to the rest of the team.
