### ISSUE TITLE
clientId is a guid, right?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/xamarin-docs#2031]
I'm pretty sure I'm supposed to put the redirect url as `msal3f748dfd-91ed-4b50-a41c-6ca5242a2043://auth` but since the example doesn't use a guid I'm not 100%.

The doc uses: `msal1234abcd://auth`.

What about updating the doc page to use a `Guid` to remove this uncertainty?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
Hi @spottedmahn,
I responded to one of your other issues with a bit more detail on why this works the way it does. There are two reasons why I didn't use a `Guid` in the doc:

First, technically I'm not sure it has to be a guid - I believe "msal123" would work. However, since that is not unique if two different applications registered to handle "msal123" URI scheme, the Android OS would not know where to route the request. So a guid is recommended.

Second, we usually avoid putting real values such as a guid into docs. It is easy to misunderstand if a guid value is the specific value that must be used or just an example!
