### ISSUE TITLE
URL scheme?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/xamarin-docs#2033]
What is the "URL scheme"?  `msal3f748dfd-91ed-4b50-a41c-6ca5242a2043://auth`?

Can we add a concrete example to remove the uncertainty?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#register-your-mobile-application-with-azure-active-directory-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by spottedmahn** [comment]
`<data android:scheme="msal3f748dfd-91ed-4b50-a41c-6ca5242a2043://auth" android:host="auth" />"`

Like that?

**Comment by spottedmahn** [comment]
nope, like this: `<data android:scheme="msal3f748dfd-91ed-4b50-a41c-6ca5242a2043" android:host="auth" />`

full file for reference:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.xamarin.adb2cauthorization">
  <uses-sdk android:minSdkVersion="15" />
  <application android:label="ADB2CAuthorization">
    <activity android:name="microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msal3f748dfd-91ed-4b50-a41c-6ca5242a2043" android:host="auth" />"
      </intent-filter>
    </activity>"
  </application>
</manifest>
```

**Comment by spottedmahn** [comment]
source of format: https://github.com/Azure-Samples/active-directory-b2c-xamarin-native#optional-step-6b-configure-the-android-project-with-your-apps-return-uri

**Comment by spottedmahn** [comment]
PR Submitted: https://github.com/MicrosoftDocs/xamarin-docs/pull/2035

**Comment by profexorgeek** [comment]
Hi @spottedmahn,
I actually had some confusion around that myself when I was creating the sample. It looks like you figured it out but here's some additional information about why it works that way:

* When completed a successful authentication will request a URL similar to your first comment. It can't use a scheme like "http" because there are already registered applications that handle that URI scheme (the browser) and it needs to return control to the application
* So MSAL creates a unique scheme with the "msal" prefix and a guid to guarantee it's unique
* When auth is complete and it requests the custom URI scheme, the Android OS knows that the browser can't handle that scheme so it checks to see if any applications have registered to handle the unique scheme
* The manifest entry lets the Android OS know that this application can handle requests for both the "msalxxx-xxx-xxx" scheme and the "auth" host so the Android OS returns control to the application.
* The "msal" and "auth" parts of the address are split in the manifest because they are technically different segments of the request - the scheme and the host!

Hopefully that helps explain the why behind the format. Thanks for your issue and PR.

**Comment by spottedmahn** [comment]
thanks for the nice detailed response! 👍
