### ISSUE TITLE
Error CS0246 while "Registering the platform implementations"

### ISSUE THREAD

**Issue by MitchSchulz** [MicrosoftDocs/xamarin-docs#2061]
I implemented my code like that, but i got an error in the line:
[assembly: Dependency(typeof(DeviceOrientationService))]
The Type "DeviceOrientationService" is unknown. The suggestion was to use 
1) ADD "using DependencyServiceDemos.iOS" OR
2) WRITE [assembly: Dependency(typeof(DependencyServiceDemos.iOS.DeviceOrientationService))]
I think the documentation is smaller and better to read like it is now, but at the end it's better to be complete and correct (without compiler errors) than easier to read. May be you include one of the Methods to be clear.  I would prefer the second one, because it's more directly visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [Xamarin.Forms DependencyService Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MitchSchulz 

The Xamarin docs tend to be sample driven, in that we distribute working samples with each doc. Because of that, we often tend to leave out some of the required `using` statements, for brevity's sake.

Having said that, your suggestion is a good one and so I've modified the doc to read as per your second suggestion. It'll go live in a PR later.

Thanks for the heads up.
