### ISSUE TITLE
static database reference is incorrect

### ISSUE THREAD

**Issue by mattkenefick** [MicrosoftDocs/xamarin-docs#2087]
The area "static TodoItemDatabase database;" should read  "static SQLiteAsyncConnection database"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
Investigated and verified this. The documentation references a singleton pattern that exposes a `Database` property and has a backing `database` field. However, the `database` field is later used as an instance of `SQLiteAsyncConnection`.

I suspect the sample was updated and then the doc was updated to match but this singleton language was missed?

**Comment by profexorgeek** [comment]
@mattkenefick I started to update this doc based on your comment and my quick investigation. However, I realized that the doc is correct but a little confusing. This line:
> `static TodoItemDatabase database`

is in the **App.cs** file. It is an instance of `TodoItemDatabase` and exposes the database as a singleton to the rest of the application. This is a bit confusing because **TodoItemDatabase.cs** has this line:

> `readonly SQLiteAsyncConnection database;`

The doc is correctly referencing the fact that **App.cs** exposes an instance of `TodoItemDatabase`. It's just confusing because a similar line with the same variable name exists in the **TodoItemDatabase.cs** file.

**Comment by decenttaro** [comment]
@profexorgeek How did you solve the problem? App.cs file is giving me an error for the database = new TodoItemDatabase();
ERROR  = Cannot be assigned to -- it is read only

**Comment by profexorgeek** [comment]
The latest version of the Todo application has a lazy intialization system that is kicked off when the `Database` property is accessed for the first time:

```csharp
static TodoItemDatabase database;
public static TodoItemDatabase Database
{
    get
    {
        if (database == null)
        {
            database = new TodoItemDatabase();
        }
        return database;
    }
}
```

Make sure you are referencing the latest sample as I just updated it last month. The app.xaml.cs file is here:
https://github.com/xamarin/xamarin-forms-samples/blob/master/Todo/Todo/App.xaml.cs
