### ISSUE TITLE
Mono.Data.Sqlite vs Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by dmitrymal** [MicrosoftDocs/xamarin-docs#2143]
Obviously, this is based on Mono.Data.Sqlite package. What about Microsoft.Data.Sqlite? 
In our apps we are using Microsoft.Data.Sqlite and it works just fine. We are wondering, is it officially supported (if 'yes', is there any official documentation specifically for Xamarin development)? 

Thank you!
CompaNova LLC
https://www.companova.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4188a42d-978f-7db4-9af0-5a032ea10610
* Version Independent ID: ce1f107a-addb-32ab-e660-0114bd5f3c14
* Content: [Using ADO.NET with Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/data/using-adonet?tabs=macos#feedback)
* Content Source: [docs/ios/data-cloud/data/using-adonet.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/data-cloud/data/using-adonet.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
**Mono.Data.Sqlite** ships with Xamarin, and is a simple 'check' in the project references to use it in your apps. 

I am not familiar with **Microsoft.Data.Sqlite**, although a quick look at their GitHub suggests the API surface is similar to the built-in library. Since it exists within the aspnet/entityframeworkcore repository, you should probably check with them whether they intend for it to be used with Xamarin? It's worth noting that it depends on [SQLitePCLRaw.bundle_green](https://www.nuget.org/packages/SQLitePCLRaw.bundle_green/), which is also used by the popular Xamarin library "sqlite-net".

We definitely do not have any pages for that library within the Xamarin documentation.

Also, both libraries are open-source, you can view the source code the [Mono version](https://github.com/mono/mono/tree/master/mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0) and the [ASPNET version](https://github.com/aspnet/EntityFrameworkCore/tree/master/src/Microsoft.Data.Sqlite.Core).

**Comment by dmitrymal** [comment]
@conceptdev Thank you for explaining this. 
Just out of curiosity, with .NET 5 announced (https://devblogs.microsoft.com/dotnet/introducing-net-5/) are there any plans to move from Mono implementation to .NET Core for Xamarin? (which would also include Sqlite implementation) Or is too far down the road?

Thank you!
CompaNova LLC
[https://www.companova.com](https://www.companova.com)

**Comment by bricelam** [comment]
Microsoft.Data.Sqlite is supported on Xamarin.

See these Microsoft.Data.Sqlite docs:

* [Comparison to System.Data.SQLite](https://github.com/aspnet/EntityFramework.Docs/blob/master/msdata-sqlite/compare.md) (and Mono.Data.Sqlite)
* [Xamarin](https://github.com/aspnet/EntityFramework.Docs/blob/master/msdata-sqlite/xamarin.md)

**Comment by conceptdev** [comment]
Thanks for the info @bricelam, going to check those links out!

**Comment by conceptdev** [comment]
@dmitrymal you can see "Xamarin" in the block architecture diagram on the [blog post](https://devblogs.microsoft.com/dotnet/introducing-net-5/) you linked 😉

**Comment by conceptdev** [comment]
So I _can_ confirm that the Microsoft.Data.Sqlite NuGet works with Xamarin – I've tested it locally with the example from [this page](https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/data/using-adonet?tabs=macos#feedback).

Unfortunately, the Microsoft NuGet and the SQLite-NET NuGet have conflicting dependencies, so I can't successfully add them _both_ to the same sample for demo purposes. For now, I'm just going to add a mention of `Microsoft.Data.Sqlite` to the page text, with the links provided by @bricelam. 

Many of our customers use SQLite-NET for it's simple ORM capability, so that's what I'm keeping in the sample.
