### ISSUE TITLE
Android Emulator - Needs Chrome for this to work

### ISSUE THREAD

**Issue by bradyguy** [MicrosoftDocs/xamarin-docs#2159]
In order to get this tutorial to run correctly I had to install chrome on the android emulator.   Before I did that I could sign up then I would get a blank black screen.   I could restart the app in the emulator and login and would again get a blank black screen.   After reading several articles and trying other samples for azure b2c I ran across a sample that required chrome to be installed.  After I installed chrome (and that sample didn't work) I came back to this one and observed that the sample now works as expected.   I also saw something that app.uiparent (this, true) might work but I couldn't get that to work.   

I would also find it helpful to have more insight on how the msal{clientid}://auth redirect actually works.  The under the hood description.

/Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by bradyguy** [comment]
Update: I removed chrome from the emulator and then added the .WithUseEmbeddedWebView(true) to the onLoginButtonClicked method.  And that seems to work without the app.uiparent (this, true)  in the mainactivity.

result = await App.AuthenticationClient
                    .AcquireTokenInteractive(Constants.Scopes)
                    .WithPrompt(Prompt.SelectAccount)
                    .WithParentActivityOrWindow(App.UIParent)
                    .WithUseEmbeddedWebView(true)
                    .ExecuteAsync();

**Comment by profexorgeek** [comment]
Regarding how MSAL works, I didn't add that to this doc because it's not actually unique to MSAL - it's a core part of how platform OS route requests. On Android, this is called an `Intent` and you can read about them here:
https://developer.android.com/reference/android/content/Intent

Here's what's happening under the hood:

The auth process leaves your application to authenticate using a browser. When that is complete, the Android OS must somehow return control to your application. This comes in the form of an `Intent` that includes an `action` and `data` (technical terms in this context).

Your application must register with the Android OS to handle this _specific type_ of `Intent`. The OS uses the URL Scheme as part of the filtering process to figure out how to route the request to an application. You must ensure that other applications aren't registered to handle the returning auth request URL Scheme or control will never return to your application! For example if the scheme was `http://` or `tel://` other applications would already be registered as the default handlers for that scheme.

So MSAL defines a convention where the URL Scheme is specified as "msal" + [some guid] + "://". This is configured in Azure as the redirect URL. So when the auth request is completed:

1. Azure redirects to the unique URL scheme
1. Android OS creates an `Intent` containing the URL scheme as `data`
1. Android OS checks for applications registered to handle the unique URL Scheme and finds your app
1. Android OS returns control to your app with the payload data from the Azure auth process
1. MSAL library automatically parses the returning request for you and authenticates the user

I'm going to close this thread. If you are still having problems please tag me in a comment!
