### ISSUE TITLE
Issues with the documentation on updating component references to Nuget as it doesn't mention what to do if using Visual Studio 2019

### ISSUE THREAD

**Issue by johnfredrick** [MicrosoftDocs/xamarin-docs#2169]
I'm having a hard time telling which are component references or nuget packages as there is no "components" folder under any of my projects(platform-specific or platform-agnostic).I'm using Visual studio 2019 version 16.2.4.

**Comment by conceptdev** [comment]
Can you please share with documentation you are referring to? Thanks!

**Comment by johnfredrick** [comment]
https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/component-nuget?tabs=windows.

**Comment by conceptdev** [comment]
@johnfredrick as the page mentions, Xamarin Components were discontinued in 2018, so there will be no **Components** folders in the latest versions of Visual Studio. This is by design.

![no-components](https://user-images.githubusercontent.com/199373/71749462-6074e880-2e2a-11ea-8fdb-e67eb7cc604c.png)

if you haven't already resolved your question, please open a new issue. As the page explains, component references are a specific kind of XML element in your **.csproj** so you _should_ be able to identify components by inspecting the **.csproj** file in a text editor.
