### ISSUE TITLE
Loading Files Embedded as Resources

### ISSUE THREAD

**Issue by Delog-ru** [MicrosoftDocs/xamarin-docs#2185]
Error in section "Loading Files Embedded as Resources". 
Instead of code:
WorkingWithFiles.PCLTextResource.txt
It must be:
WorkingWithFiles.Resources.PCLTextResource.txt
I added "Resources" after namespace

P.S. There is easier way to read resources:
Properties.Resources.YourResourceName;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51f9e390-1b2e-fe0b-3969-8feb203d9fb8
* Version Independent ID: 714d5991-0577-4d86-3585-bed8788e73cf
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/files?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/data/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/files.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Delog-ru 

The code in this article is from the [sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/workingwithfiles/) the doc links to, and having checked it, is accurate.

I guess that your resources are in a Resources folder, which is why you had to add that to the resource ID (as explained at https://docs.microsoft.com/xamarin/xamarin-forms/data-cloud/data/files?tabs=windows#organizing-resources).
