### ISSUE TITLE
A problem with the redefined AnchorY equation

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#2188]
In the [Scaling and Rotation with Anchors](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple#scaling-and-rotation-with-anchors) section 
The equation:

```csharp
image.AnchorY = (Math.Min (absoluteLayout.Width, absoluteLayout.Height) / 2) / image.Height;
await image.RotateTo (360, 2000);
```
is not always correct, especially when the view is at the end of the layout, I tried to modify it, but it's a bit complex, and I don't understand it, for example, why dividing by `image.Height`, 
shouldn't it be the half of the layout height (or width) minus the distance between the top image and the top (or the right) bound of the layout to obtain the distance between the top image and the center of the layout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fb76e26-b365-76c2-6a8c-c35c03e7fb2b
* Version Independent ID: 9cefc858-4798-c05f-f7ae-7dedf7e5522a
* Content: [Simple Animations in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple)
* Content Source: [docs/xamarin-forms/user-interface/animation/simple.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/animation/simple.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mshwf 

You've raised a valid point. The sample wasn't performing correct calculations, so I've simplified its layout and hopefully made it clearer in the process.

So now the sample has a `ContentPage` that only has an `AbsoluteLayout` on it, which contains an `Image`. There's an `OnSizeChanged` handler which saves the centre of the `AbsoluteLayout` as a `Point` field named `center`, and which saves the distance from the centre to the nearest edge as the `radius`. The `OnSizeChanged` handler concludes by positioning the `Image` in the horizontal center of the page, but with its top edge a distance of `radius` above the center of the `AbsoluteLayout`.

Rotating the `Image` around the `center` then becomes a case of setting `AnchorY` to a value from the top of the `Image` to the centre point, but in units of the image's height. `AnchorX` doesn't require setting because its default value of 0.5 is fine.

Hope this helps!
