### ISSUE TITLE
What's the purpose of MessagingCenter?

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/xamarin-docs#2207]
The docs should explain why and when you should choose to use MessagingCenter. Why not just use standard events? If you're worried about strong references being created, you can use WeakEventHandlers.

Using loosely typed strings like this means you can't refactor your code, so what's the benefit of MessagingCenter vs WeakEventHandlers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @andrewleader 

The purpose of MessagingCenter is to reduce dependencies between publishers and subscribers, to avoid the memory management issues that can result from strong references.

Some developers choose to use MessagingCenter because it's built into Xamarin.Forms. Others choose not to because of its reliance on magic strings, although this can be mitigated slightly by defining them as constants.

Using a third party weak event manager is an option, but adds to the number of assemblies that must be loaded at startup, which can be problematic on Android.

I've added a clarification to the doc, in a PR that will go live later.

**Comment by andrewleader** [comment]
Makes sense, thanks David. Why doesn't Xamarin add a weak event manager implementation into Xamarin.Forms? Then there wouldn't be the concern about another assembly being loaded, and it seems like weak event handlers are the best choice with the only current drawback being that they're not included in Xamarin.Forms itself?

**Comment by davidbritch** [comment]
Afraid that a weak event manager would be so far down the list of priorities that I'm doubtful it will ever happen. It just doesn't feature in user requests at all.

**Comment by andrewleader** [comment]
Strange, then why was MessageCenter added? Doesn't it serve the exact same purpose, however has the (debatable) drawback that it's loosely typed rather than strongly typed?
