### ISSUE TITLE
The property 'Visual' was not found in type 'ContentPage'.	

### ISSUE THREAD

**Issue by johnfredrick** [MicrosoftDocs/xamarin-docs#2226]
Followed the docs on adding Visual to my Xamarin.Forms Project. Despite adding the Xamarin.Forms.Material Visual nuget package and initializing the material renderer for the Android Project, the "Visual" Property is unavailable from the ContentPage.  Im using Xamarin.Forms version 4.2.0.848062 and Xamarin.Forms.Visual.Material with the same version and Visual Studio 2019 version 16.2.4.

**Comment by davidbritch** [comment]
HI @johnfredrick 

Visual has been part of Xamarin.Forms since Xamarin.Forms 3.6, and the `Visual` property is available without adding additional NuGet packages.

It's most likely that this is a Visual Studio issue, that will go away with some combination of relaunch, ensuring all projects are using the same NuGet packages, and deleting the bin/obj directories for each project.

If in doubt, you can also try the sample that the Visual doc links to.
