### ISSUE TITLE
Device.StartTimer vs System.Threading.Timer

### ISSUE THREAD

**Issue by leotsarev** [MicrosoftDocs/xamarin-docs#2243]
What's a benefits or drawbacks of using Device.StartTimer vs System.Threading.Timer? Both are firing on background threads, both are cross-platform and netstandard2 compatible. System.Threading. Timer has a bonus points of being non-Xamarin specific.
What should I use and when? I think it worth at least mentioning there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e81aa61e-e932-f169-b7ed-83cecfd6702d
* Version Independent ID: 08d4698a-1d94-e4c3-bf87-9f1a73892a67
* Content: [Xamarin.Forms Device Class - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/device#feedback)
* Content Source: [docs/xamarin-forms/platform/device.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/device.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @leotsarev 

Use either.

`Device.StartTimer` was implemented long before .NET Standard came along, and in those days the `Timer` class was unavailable to PCL projects. Now that the `Timer` class is available, there's no advantage/need to use `Device.StartTimer`. But that API won't vanish,  because there will be older projects that still rely on it.

I'll make an update to the Device doc.
