### ISSUE TITLE
Hi, do you have example URI scheme for apple IOS?

### ISSUE THREAD

**Issue by rdonasco** [MicrosoftDocs/xamarin-docs#2274]
I tried the example for android and it works. However, running in IOS, the login button does not do anything. Perhaps I'm doing something wrong. 

You have example on the android manifest. &lt;!-- &lt;data android:scheme="msalaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" android:host="auth" /&gt; --&gt;

Do you have sample pattern for the URI scheme that we're supposed to put in the Info.plist? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by rdonasco** [comment]
Tracing the code shows the error ex.ErrorCode is "authentication_cancelled". The login page of B2C did not even show up :(

**Comment by profexorgeek** [comment]
Hi @rdonasco, 
After the app authenticates with ADB2C, the user will be redirected back to the URL scheme. This URL will look something like a web browser URL but instead of "http" or "https" it will use a custom scheme so the operating system can route the request back to your app. The whole URL will look something like this:
`msalaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee://auth`

In the Android manifest this is split into the **scheme** and **host** arguments. However, on iOS I believe you put the whole scheme in there. So I think you are just missing the `://auth` from the end.

The "authentication_cancelled" may indicate a different problem. Make sure you are using manual provisioning and have included the `Entitlements` file. See the MSAL docs about iOS here if you're not sure what that means:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-iOS-specifics

Please let me know if this helps you get it working!

**Comment by rdonasco** [comment]
Hi,

Thanks. Got it working.

Cheers,
Roy

**Comment by vdarrel** [comment]
Using this url scheme works perfectly while debugging. However when I try to upload it to the app store I get the following error:
The following URL schemes found in your app are not in the correct format: [msalaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee://auth]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail. I replaced my actual application id with the example letters.

**Comment by robertwood62** [comment]
I too have the same error appearing when I try to deploy this to the app store.
