### ISSUE TITLE
This documentation and the demo no longer work

### ISSUE THREAD

**Issue by n8allan** [MicrosoftDocs/xamarin-docs#2326]
To make this work, you have to invoke .WithRedirectUri("msal&lt;client id&gt;://auth") when creating the AuthenticationClient in the main app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
@n8allan it looks like the sample is built against v4.0.0 of the MSAL library. The current version is 4.7.1. Can you clarify:

- Which Microsoft.Identity.Client Nuget package you had this issue with?
- Which platform you had the issue with?

I tested this across platforms and it worked at the time so I'm curious if a minor revision update introduced breaking changes or if there's some other issue I missed. I'd like to repro with the same version and platform you used.

**Comment by profexorgeek** [comment]
@n8allan Disregard the questions in my last comment. I just found this thread, which has more detail:
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/28

I'm still investigating this. Our doc/sample relied on setting a custom redirect URI in the Azure portal, which _should_ redirect control back to the application without requiring the `WithRedirectUri` method call. I want to understand this change so I can note it in the doc for future users.

**Comment by profexorgeek** [comment]
Hi @n8allan I have updated our sample and docs changes will be rolling out shortly. Thanks for bringing this to our attention.

One thing I found was that our sample worked for me, without specifying the `WithRedirectUri`. I'm relatively sure this is because my Azure test instance only had a single redirect URI and so it redirected back to that by default when auth was completed. However, if you have multiple Redirect URIs and do not supply the `WithRedirectUri` clause, Azure does not know where to redirect the request after auth is complete. I have updated the docs with a note about this!

Thanks again.
