### ISSUE TITLE
How to Set Linker to Don't Link

### ISSUE THREAD

**Issue by brent-p** [MicrosoftDocs/xamarin-docs#2347]
According to the page:
"Set the linker to Don't Link for the best experience. The Link SDK only setting works most of the time, but it may fail in certain cases."

Can you provide the steps involved to change the linker setting e.g. where is this setting located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by brent-p** [comment]
Also what are the consequences/trade offs in setting the app to don't link? Will this affect other parts of building/debug process? Is there anything new I now have to do?

**Comment by davidbritch** [comment]
Hi @brent-p 

Linking is used to reduce the size of your application. It's normal to have the linker turned off for debug builds, but turned on for release builds. Linking adds to the build time, which is why it's switched off for debug builds.

For more info, see [Linking on Android](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker) and [Linking on iOS](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=macos).

**Comment by brent-p** [comment]
Hello @davidbritch thanks for your response. It may be helpful for others if you put "For more info, see Linking on Android and Linking on iOS." at the end of the "Set the linker to Don't Link for the best experience. The Link SDK only setting works most of the time, but it may fail in certain cases." line. I know I had to hunt on google for where to change it.Cheers

**Comment by davidbritch** [comment]
^ @maddyleger1
