### ISSUE TITLE
In VS 2019 Community, there are NO tabs for Packaging or Linker or Advanced.

### ISSUE THREAD

**Issue by mkamoski** [MicrosoftDocs/xamarin-docs#2350]
In VS 2019 Community, there are NO tabs for Packaging or Linker or Advanced.

I am looking under Android Options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26d346ac-9d17-d567-9c22-4350aca4b071
* Version Independent ID: bd0e55c1-7f38-fdf4-a5d0-763ce75d8604
* Content: [ProGuard - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows&source=docs#feedback)
* Content Source: [docs/android/deploy-test/release-prep/proguard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/release-prep/proguard.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Hi @mkamoski, this seems like it might be a bug? I've created an [issue on developer community](https://developercommunity.visualstudio.com/content/problem/853313/android-solution-properties-options-tab-missing-su.html) – does that reflect your experience as well?

**Comment by mkamoski** [comment]
> Hi @mkamoski, this seems like it might be a bug? I've created an [issue on developer community](https://developercommunity.visualstudio.com/content/problem/853313/android-solution-properties-options-tab-missing-su.html) – does that reflect your experience as well?

Yes.

**Comment by conceptdev** [comment]
UPDATE: the engineering team showed me that the tabs are now 'flattened' into one page - the linker information is below the packaging properties, and the advanced information is now reached by a button rather than a tab (new screenshot below). Updating the doc screenshot soon.

![no-tabs-ok](https://user-images.githubusercontent.com/199373/70735261-b7235280-1cc2-11ea-85fd-fd5dcf4d4e4a.png)

Thanks for letting us know!
