### ISSUE TITLE
Loading demo not working for iOS

### ISSUE THREAD

**Issue by john-dalsgaard** [MicrosoftDocs/xamarin-docs#2355]
... which I finally found out when trying to troubleshoot why it didn't work in my own app. 

The firing of the events are not working consistently for WebView :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=macos#feedback)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @john-dalsgaard 

I tried the [sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-webview/) which implements the loading demo, and as far as I can see there aren't any problems.

What's your issue? Part of the problem may be tat because the `LoadingLabelXaml` page is displayed in a `TabbedPage`, it's actually loaded at app launch. So the events fire before you get a chance to switch to the `LoadingLabelXaml` page.

**Comment by john-dalsgaard** [comment]
Sorry, I didn't get back to you sooner. You may be quite right - as per your explanation. I've just been so hung up by dev. :-)
