### ISSUE TITLE
NuGet link is broken and the NuGet package is still prerelease.

### ISSUE THREAD

**Issue by ericlee1974** [MicrosoftDocs/xamarin-docs#238]
For the section of FirebaseJobDispatcher,
the link at the bottom of the article under Related Links is broken :

https://www.nuget.org/packages/Xamarin.FirebaseJobDispatcher

The initial link in the body of the article works, but there is an updated version. 
https://www.nuget.org/packages/Xamarin.Firebase.JobDispatcher/0.7.0-beta1

As you can see, the package is only prerelease at the moment and I found I couldn't update it using the 'Manage NuGet Packages for solution' in Visual Studio 2017. I had to use package manager console as indicated in the link. Is it ok to use the prerelease version for a production app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf37247-a5cb-c988-7577-a50e0cd6a0c9
* Version Independent ID: 5c6955b2-8466-0a64-3981-bc8189569cdf
* Content: [Firebase Job Dispatcher - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/firebase-job-dispatcher)
* Content Source: [docs/android/platform/firebase-job-dispatcher.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/firebase-job-dispatcher.md)
* Service: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by topgenorth** [comment]
Hi there, thanks for reporting the broken link; I'll fix that up right away.

However the story for updating the binding is not as happy. There is an [outstanding bug (59046)](https://bugzilla.xamarin.com/show_bug.cgi?id=59046) which prevents the binding from being updated.  

Because the current binding is for an old version of the Firebase JobDispatcher, I'd be a bit reluctant to say it's safe for production at this point. If possible, I would suggest using the [Android JobScheduler API](https://docs.microsoft.com/en-us/xamarin/android/platform/android-job-scheduler) instead.

**Comment by wyattblake** [comment]
has this package been removed?  I'm trying update my project to compile against Pie and when I try to build this on a build server it fails to get the package.
