### ISSUE TITLE
Android setup no longer reliably works for receiving push notifications when app is closed

### ISSUE THREAD

**Issue by FrankSzendzielarz** [MicrosoftDocs/xamarin-docs#2451]
Please see the following for more info: https://stackoverflow.com/questions/59582314/how-can-i-receive-a-push-notification-when-my-xamarin-android-app-is-stopped

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#configure-the-android-application-for-notifications)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @FrankSzendzielarz,
Thanks for opening this issue. I read the SO post you linked. It seemed like the biggest problem was understanding the difference between "backgrounding" an app and the force-close that happens when debugging is stopped. I'm adding a note about that to the article's testing tips and will be publishing that shortly.

If you have more specific feedback on this article or sample, please post another issue.
