### ISSUE TITLE
NuGet package does not exist :(

### ISSUE THREAD

**Issue by iforlife** [MicrosoftDocs/xamarin-docs#247]
Can't find it at all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Service: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by topgenorth** [comment]
Thanks for reporting this; I can't find Xamarin.LiveReload at NuGet.Org either.  We're looking into this.

**Comment by topgenorth** [comment]
Hi there.  Just to add some clarity to this: The Xamarin.LiveReload package isn't available on nuget.org (which is why I couldn't see it there).  Instead, you have to make sure that you install Xamarin Live Reload VSIX.  The, in Visual Studio, when you go to add the Xamarin.LiveReload package, you have to make sure that the Package Source dialog is set to **All** (and _not_ **Nuget.org**).  Then you should be able to search and install the Nuget package.

**Comment by esarmientocoba** [comment]
Good day, 
The package Xamarin.LiveReload  does not appear, I have performed the steps as indicated by microsoft on your page and the result is the same ... please check the availability of the package so that we can make use of it in our application developments

**Comment by iforlife** [comment]
@topgenorth , please check your sources in NuGet manager - you must have something special in there that we don't :) Or better yet, just move the package to NuGet.org and all will be ok.

**Comment by topgenorth** [comment]
@iforlife / @esarmientocoba : The only other tip/trick I can give you is to check the contents of the *Package Source* dialog. If you don't see *Live Reload* as a package source, then something went wrong with the VSIX installer.

If you're still unable to install LiveReload, the problem is more significant than an error in the documentation. Please go to   [Developer Community](https://developercommunity.visualstudio.com) and raise an issue there. We can't provide much technical support here as this repo is to raise issues/suggest improvements with documentation. 

Sorry I couldn't do much more for you!

**Comment by tlhintoq** [comment]
If you search for xamarin.livereload through Nuget Package Manager GUI the package isn't found. (Yes I have the pre-release check ticked on)
If you use the Nuget Package Manager Console and issue the command:
install-package xamarin.livereload -prerelease -project myprojectname
It installs fine.

**Comment by btastic** [comment]
In case anyone needs the package source url, it was this after installing: https://nugetized.blob.core.windows.net/live-reload/index.json

**Comment by djaus2** [comment]
I found that tlhintoq comment worked for me.
Couldn't find the package in the GUI but Console approach worked.
Using VS 2017 15.8.0 Preview 3.0 (Enterprise VS)

LiveReload.Init();  LiveLoad recognised in App.cs 
App built and run but no live update of UI on XAML  save.
