### ISSUE TITLE
Two classes with same name.

### ISSUE THREAD

**Issue by BillyMartin1964** [MicrosoftDocs/xamarin-docs#2470]
I don't understand how you can have both a class and a static class with the same name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases?fbclid=IwAR1ADOm2VDCmLCJ3uXVE1CstcAyb1N4xOd_ZE9IAiSz0SD3W6cstvqIl2tU#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @BillyMartin1964,
There aren't two classes. It took me a bit to spot what you are talking about but this is a mistake in the doc!

There is one `TodoItemDatabase` class and it is not static. The doc discusses this class in two different sections because the first section focuses on initialization and the second section focuses on data manipulation. The second section is marked as `static` but this is an error.

I'm assigning this to myself to fix. In the meantime, the sample project is correct if you want to download that and check it out!

Thanks for catching this.

**Comment by profexorgeek** [comment]
I fixed this and it will be publishing soon. Thanks again for the catch.

**Comment by BillyMartin1964** [comment]
Thanks for the fast response. I'm trying to follow your code, but the example is too basic. I can't figure out how to use this with multiple models, a viewmodel, and generics. Is there an example anywhere? I don't know of anyone who could put out an app with no viewmodel and only one model. LOL Thanks, though.

**Comment by profexorgeek** [comment]
We have a section in our docs on Data Binding:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/

We also have a free book that has a robust section on MVVM:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/
