### ISSUE TITLE
clr-namespace cannot reference mscorlib

### ISSUE THREAD

**Issue by WoMart** [MicrosoftDocs/xamarin-docs#2475]
In the **x:Static Markup Extension** section, clr-namespace is introduced, and System referenced. 
`xmlns:sys="clr-namespace:System;assembly=mscorlib"`

I cannot reference mscorlib in my projects.  The closest I can get is:
`xmlns:sys="clr-namespace:System;assembly=netstandard"`

I can't find any answer to this in the docs and online. Frankly, I'm not sure what to look for in the first place, apart for obvious keywords. Could you explain what's happening and maybe add a note to the article to clarify future confusion?

**Comment by davidbritch** [comment]
Hi @WoMart 

Both you and the article are correct! Here's the explanation why.

.NET framework has mscorlib, but .NET core doesn't. The sample/doc was originally written in the .NET framework days. However, the sample is now using .NET core and intellisense objects to `xmlns:sys="clr-namespace:System;assembly=mscorlib"`(because mscorlib doesn't exist). However, the sample still builds and runs as expected. The reason for this is at runtime any mscorlib references are type forwarded to the netstandard assembly.

Having said all that, the best solution is as you've identified - to use `xmlns:sys="clr-namespace:System;assembly=netstandard"`. I'll get the doc/sample updated to use this today.

Thanks for bringing this issue to my attention.

**Comment by davidbritch** [comment]
I've now updated the samples and the docs. However, the doc updates are in a PR that will go live later.
