### ISSUE TITLE
This document could cover Face ID as well if the needed Info.plist entry is added. 

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/xamarin-docs#248]
If one follows this guide and runs the resultant app on an iPhone X, it will crash with a native SIGABRT error when the "Add a Chore" button is pressed. This is because Face ID requires a Usage Description in the Info.plist file as follows:

&lt;key&gt;NSFaceIDUsageDescription&lt;/key&gt;
&lt;string&gt;String to be displayed in alert when iOS asks user for permission to use Face ID&lt;/string&gt;

With the above addition, this guide could be used for Face ID as well. 

Might be worth linking to this sample as well:
https://developer.xamarin.com/samples/monotouch/ios11/FaceIDSample/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9834f926-e2ef-ecb6-b2bb-4924db44f25e
* Version Independent ID: c7d3382a-c41f-87c1-3632-3738df7b2fa9
* Content: [Touch ID - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/touchid)
* Content Source: [docs/ios/platform/touchid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/touchid.md)
* Service: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @jgold6, thanks a bunch for calling this out. 

- I've [updated](https://github.com/xamarin/ios-samples/pull/245) the [Storyboard Tables – Local Authentication](https://developer.xamarin.com/samples/monotouch/StoryboardTable_LocalAuthentication/) sample so that it has the `NSFaceIDUsageDescription` key, and linked to this sample more clearly in the text of the doc. These link updates should be published soon.
- I've filed an issue on our internal backlog to update this doc more thoroughly to discuss FaceID, since this is a pervasive change.
