### ISSUE TITLE
So nearly 3 years after after this page was created, Xamarin.Forms 4 Mac is still on Preview

### ISSUE THREAD

**Issue by JohnH-FF** [MicrosoftDocs/xamarin-docs#2526]
Any update on this? Will it ever leave preview?
Or is this yet another example of Xamarin starting something and not finishing it? At least with Live Player that project officially got canned, but we are actively using XF 4 Mac to deliver to iOS, Droid, UWP and MAC. Other than a few layout bugs it works well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a28b49-e47c-fca9-69e4-c261f2869e9a
* Version Independent ID: db9d6201-0042-eb0c-7b86-80089b543674
* Content: [Mac Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac)
* Content Source: [docs/xamarin-forms/platform/other/mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/mac.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by shudson302** [comment]
I would also like to know if this will ever be out of preview.

**Comment by kwypto77** [comment]
I agree.  Mac support is one of the main reasons that we went with Xamarin.Forms.

**Comment by davidbritch** [comment]
Afraid all I can do is point you to the [XF for Mac status page](https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status).

**Comment by JohnH-FF** [comment]
@davidbritch thank you for the link David, can you point us in the direction of who/where we should escalate this? Your efforts as always are appreciated. :)

**Comment by davidbritch** [comment]
@JohnH-FF Best to contact David Ortinau or Paul DiPietro (both Forms PMs).

**Comment by JohnH-FF** [comment]
@shudson302 @kwypto77 I have asked a question on the Xamarin.Forms forum: [https://forums.xamarin.com/discussion/177786/when-will-xamarin-forms-for-mac-leave-preview/p1?new=1](url), please feel free to add your comments there too.

**Comment by shudson302** [comment]
@JohnH-FF OK thanks

**Comment by RadWes** [comment]
We have a Xamarin.Forms app that we have had for iOS and Android for a few years.  Now doing a new one for iOS, Android, and Mac.  Got the iOS and Android published to their App stores.  Mac is being rejected.  The documentation here [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac] says to make the first window closable.  In doing so, the user can close the Xamarin.Forms window, but the app continues to run. Apple will reject it.  You either have to make it so that the window is not closable, or add a confirmation prompt.  I posted the question about it in Stack Overflow. So close.... but not there yet.

**Comment by JohnH-FF** [comment]
@RadWes Thank you for the heads up!
Feel free to add your comments to the Xamarin Forum thread I mentioned above, the more people that weigh in with an opinion, the better.
