### ISSUE TITLE
Yellow On White

### ISSUE THREAD

**Issue by WDCoates** [MicrosoftDocs/xamarin-docs#2549]
Yellow on White is so hard to see!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
What specifically are you referring to in the doc, @WDCoates ?

**Comment by WDCoates** [comment]
Craig,

It's more of a general point.

Most pages I see these days in Microsoft's Docs have this, yellow text on white background. Now I don't have too bad eyesight but what about people with impaired eye-sight?

[cid:01639699-9d51-41ae-9622-14845fa1a162]

Can you tell me what the yellow writing says because I can't see it!

Microsoft also do lime green text on grey background which is almost as bad.

Regards,
D.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by conceptdev** [comment]
Thanks for the feedback @WDCoates, unfortunately your attachment fails to display, but I'm still interested to understand what you're seeing. We are committed to providing an accessible experience, and provide three different themes to help choose the best experience:

<img width="238" alt="Screen Shot 2020-02-21 at 9 59 21 AM" src="https://user-images.githubusercontent.com/199373/75059283-7f3e4580-5491-11ea-8ba5-dd563dec3de3.png">

It would be great if you could try attaching screenshots again - I would really like to understand where you are seeing yellow-on-white and lime-green-on-grey text, because it sounds like something we want to fix!
