### ISSUE TITLE
Database.TableMappings.Any(m => m.MappedType.Name == typeof(TodoItem).Name) returns false even if instantiated already

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#2550]
The instantiation of the database is done each time I launch my application. 
Since I do an insert after it is created only if it wasn't instantiated first, I get `SQLite.SQLiteException: Constraint`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @eli191,
I'm not sure I fully understand what's happening here. I can't reproduce the error you are getting. Can you povide some more info? Specific questions:

1. Are you getting this error in the sample project with no modifications? If so, let me know what type of device you are testing and any more specific information you can provide.
2. Have you modified the project or written your own? If so there could be something missed with all of the async stuff happening here. It could be that the database hasn't finished initializing?

**Comment by rickclephas** [comment]
The issue @eli191 is describing is with the following code:
https://github.com/MicrosoftDocs/xamarin-docs/blob/af31fc763794d950b4aaa4453beb09751396beb2/docs/xamarin-forms/data-cloud/data/databases.md#L114-L117

The `TableMappings` isn't something that is persisted. It's just an in-memory cache.
The first time a class is used in one of the calls it is added to the mappings.
https://github.com/praeclarum/sqlite-net/blob/ff6507e2accd79ab60aa84a1039215884e4118fa/src/SQLite.cs#L454-L471

In the provided documentation these if-statements that check the mappings don't have any effect since every time the connection to the database is recreated (e.g. the app is restarted) the mappings aren't there.

Inserting data based on this check will attempt to insert the data every time the database connection is created.
This will result in multiple records in the table or an exception due to constraint violations.

@eli191 you should await the result of the `CreateTablesAsync` call which will return the `CreateTableResult` which is either `Created` or `Migrated`. Based on these values you can insert the data only when the table is first created.

IMHO it would also be cleaner to use the `CreateTableAsync` call like so:
```c#
var createTodoItemTableResult = await Database.CreateTableAsync<TodoItem>();
```
