### ISSUE TITLE
Entry value changing when switching tab in Xamarin forms shell with visual material

### ISSUE THREAD

**Issue by tal-athena** [MicrosoftDocs/xamarin-docs#2590]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfbc90e-2eb6-a305-f7da-bded6e31a2b4
* Version Independent ID: 66cad08c-2158-c081-a668-e4dad525e664
* Content: [Xamarin.Forms Material Visual - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual#feedback)
* Content Source: [docs/xamarin-forms/user-interface/visual/material-visual.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual/material-visual.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @tal-athena,
Thanks for your comment. This repository is for Xamarin documentation and samples but it sounds like your issue is with Xamarin.Forms itself.

If you have found a bug please open an issue on the Xamarin.Forms repository here:
https://github.com/xamarin/Xamarin.Forms

If you can provide screenshots or steps it will help the engineering team find and fix the problem more quickly!
