### ISSUE TITLE
page feedback

### ISSUE THREAD

**Issue by davecalkins** [MicrosoftDocs/xamarin-docs#2627]
The "Use a Custom Font (PREVIEW)" section does not yet work as of v4.5.0.356 or the prerelease v4.6.0.379-pre1.  There's no indication of when this will be supported.  Trying to use the ExportFont attribute just results in an error.

Another issue is the sample project.  The FontPageXaml.xaml has a label which specifies the custom font on each platform.  Only, on iOS it doesn't actually specify the included font!  It specifies a completely different font, MarkerFelt-Thin as opposed to the Lobster-Regular which is included in the project and which, presumably, is the whole point of the example, i.e. showing how to use that font.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @davecalkins 

Cross-platform fonts were meant to drop as a finished feature in 4.5, but only works on iOS. If you take a look at the sample project (which uses the `ExportFont` attribute), it works on iOS.

My guess is you are accessing the sample via the samples gallery (https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/workingwithfonts/), rather than the repo (https://github.com/xamarin/xamarin-forms-samples). There's a problem at the moment whereby the samples gallery isn't having its ZIPs regenerated from the repo. However, if you look at the repo you'll see that (1) `ExportFont` works on iOS, and (2) FontPageXaml.xaml doesn't have any reference to MarkerFelt-Thin in it.
