### ISSUE TITLE
Please add a Xamarin.Forms example to send Azure notifications to specific users 

### ISSUE THREAD

**Issue by wml2017** [MicrosoftDocs/xamarin-docs#2694]
There are many people who use Xamarin.Forms to develop iOS and Android apps and want to use Azure notification hub to send push notifications to specific users. But you don't  have this example. Please provide a Xamarin.Forms example as well as its backend example how to register and send azure notifications to a specific user's iPhone and/or Android phone. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by DjeeBay** [comment]
@wml2017 you're right !
I just can't find how to send a notification to a specific user by providing his device token.

The Firebase documentation shows parameters to add in the payload ("to" or "registered_ids").
But adding them in the Azure Notification Hubs "Test Send" payload doesn't seem to work.

Is it at least possible ?

**Comment by DjeeBay** [comment]
So after hours of searching I've found where the documentation talks about it... and it's with tags :  https://docs.microsoft.com/fr-fr/azure/notification-hubs/notification-hubs-tags-segment-push-message#using-tags-to-target-users

I wasn't considering it because IMO it wasn't tags purpose.
Finally this tips needs a better visibility.

Notification Hubs interface could also display clearer tooltip near the tag's field.
Actually the tooltip says "You can send test notifications to a specific set of registrations using this option."

Which was making me considering that tags have to be used for topics, not a single device/user.

**Comment by davidbritch** [comment]
Glad you've managed to unblock yourself.
