### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by l-lemesev** [MicrosoftDocs/xamarin-docs#27]
So we did the binding, everything is fine, but what do we do next?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5521ad-2f05-4dc4-e070-fbfd2e0cd200
* Version Independent ID: cba6b549-9f01-0964-3c1f-60e825cab870
* Content: [Real-World Example using CocoaPods - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/examples/cocoapod)
* Content Source: [docs/cross-platform/macios/binding/objective-sharpie/examples/cocoapod.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/binding/objective-sharpie/examples/cocoapod.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @l-lemesev, thanks for the question. I’ll add some next steps to the bottom of this document, but in the mean time, here are a few other documents that describe the binding process and how to create a binding assembly from the .cs files and binary produced by `sharpie` (or otherwise):

- https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/overview (there's three step overview at the top of this doc)
- https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/walkthrough
- https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-c-libraries

**Comment by onurhazar** [comment]
Ok. I got ApiDefinitions.cs and a .framework file . What about next? I think we need to create a binding library project in order to copy api definitions and reference to the native framework. But when I do this and get a dll, it gives linking errors while referencing and building a xamarin project.

**Comment by bradumbaugh** [comment]
Hi @onurhazar, it sounds like you're on the right track, having generated the ApiDefinitions.cs and .framework file. The best way for you to get support with a specific binding will be to ask on [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin+or+xamarin.ios+or+xamarin.android+or+xamarin.mac) or the [Xamarin Forums](https://forums.xamarin.com/categories/ObjectiveSharpie).
