### ISSUE TITLE
Is there a way to find out if some other libraries are the problem

### ISSUE THREAD

**Issue by maxal1917** [MicrosoftDocs/xamarin-docs#2726]
I followed the steps from this page, but still got "ITMS-90809: Deprecated API Usage" notification when uploading my binaries.

Is it possible that some other libraries I'm using can be an issue, not Xamarin.Forms. Is there a way to find it? For example, I suspect that maybe Xamarin.Auth.XamarinForms maybe an issue, but maybe not. Is there a way to find out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#uiwebview-deprecation-and-app-store-rejection-itms-90809)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by jfversluis** [comment]
Hi @maxal1917! I'm sorry this doesn't work for you. However, you have now opened an issue on the Docs repository which is not entirely the right place for this :)

A lot has been written about this issue already, mainly here: https://github.com/xamarin/Xamarin.Forms/issues/9823

There has also been some documentation, which you obviously already found :) some additional documentation by the Xamarin.iOS team on this is here: https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/webview#uiwebview-deprecation

Having all that said, there are a couple of important things to make this work:
* Use all the right versions, Xamarin.Forms 4.5 stable or higher and Xamarin.iOS 13.10 or higher. If you are using Azure DevOps or App Center, make sure the right Xamarin.iOS version is selected, this requires some setup
* Set the mtouch argument for the right build configuration
* Set the linker behavior to all/full or SDK only

If you have done all those things but you still get the warning from Apple then there might be a third-party plugin that still references it. Assuming that you don't have any references to `UIWebView` or `WebViewRenderer` in your own code. One that we have identified is the Xamarin.iOS.MaterialComponents which is a dependency of the Xamarin.Forms.Visual.Material package. If you use that, please install the latest version (92.0 at the time of writing) of the Xamarin.iOS.MaterialComponents package on your iOS project for the time being. We are working on updating the dependency version from our Forms package.

If all this doesn't help you to figure it out, please find the email address on my GitHub profile and reach out then we will figure it out :) 

I'm asking @davidbritch to close this issue here, since like I said, this isn't the appropriate place for it.

Thanks!
