### ISSUE TITLE
Missing API Reference?

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [MicrosoftDocs/xamarin-docs#28]
Usually, as a developer, I like to be able to view a list of available apis, but I cannot find any such thing in this documentation.
If such a thing exists - where I could for example see the documentation for Android.Support.Wearable.Complications.Rendering - then I cannot find it.
Even the search doesn't find anything.
This makes it very hard to commit to Xamarin.
It would be nice if there was a traditional namespace/class browser here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a07b76-9d75-3a09-8fd4-82c724a37105
* Version Independent ID: 5a0064c1-50f4-8b78-35b5-141b07e93878
* Content: [Android Wear - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/wear/)
* Content Source: [docs/android/wear/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/wear/index.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Thank you @SQL-MisterMagoo: a new section has been added to this topic with links to the most import Wear APIs (the changes should be published in the next day or so). Because [Xamarin API documentation](https://developer.xamarin.com/api/root/MonoAndroid-lib/)  does not currently support Wear, this new content links to the definitive Android API docs for Wear namespaces and classes.
