### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#2828]
1) The documentation says the following about GetLastKnownLocationAsync: "You can get the last known location of the device by calling the GetLastKnownLocationAsync method. This is often faster then doing a full query, but can be less accurate and *may return null if no cached location exists*."

a) In what scenario can a 'no cached location exist'? Is this a frequent occurrence?
b) In regard to a), if returning null is a frequent occurrence, is the recommended pattern to first try to get a cached location, and if it fails do a real lookup?
c) How often is this cached value updated, and under what conditions?
d) Wherefrom does it draw the cached result? From a call to GetLocationAsync, or some internal update?

2) The documentation says the following about GetLocationAsync: "To query the current device's location coordinates, the GetLocationAsync can be used. It is best to pass in a full GeolocationRequest and CancellationToken since it may take some time to get the device's location."

a) What does passing in "a full GeolocationRequest" mean?
b) There is no overload that takes a CancellationToken, just a time span.
c) The code snippet following the above recommendation does not do what the recommendation says, as it is lacking any kind of timeout.
d) It is unclear what happens when the timeout is triggered -- will it return null, or will it return some kind of 'best match'?
e) Assuming some kind of location will be returned even with a short timeout, what kind of ballpark figure for timeout would be in any way acceptable?

My use case is that I just want to get the current geo location of the user for a REST call. My current pattern is to first try to get a cached position and if it fails with null, then request for a position with a three second timeout and medium accuracy. Is this an acceptable pattern, that would at worst give _some kind of result within three seconds_? Furthermore, will this 'best it could do in three seconds' result be returned in successive GetLastKnownLocationAsync calls? I just need to get the current location (whether it's cached or not) and can't wait a minute for an update. The documentation leaves more questions than answers atm for whether this pattern would accomplish that.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Answers inline:
On LastKnownLocationsAsync()
a) In what scenario can a 'no cached location exist'? Is this a frequent occurrence?
**A specific API is called on each platform to get the cached location. The OS is in charge of it. on Android we call GetLastKnownLocation, and iOS we check to see if CLLocationmanager has a location set, and on UWP we set AllowFallbackToConsentlessPositions**
b) In regard to a), if returning null is a frequent occurrence, is the recommended pattern to first try to get a cached location, and if it fails do a real lookup?
**This would be the recommended path, and also to check the timestamp**
c) How often is this cached value updated, and under what conditions?
**The OS decides, so a timestamp should be checked**
d) Wherefrom does it draw the cached result? From a call to GetLocationAsync, or some internal update?
**Internal**

On LocationAsync()
a) What does passing in "a full GeolocationRequest" mean?
**You can send in parameters to specify the request**
b) There is no overload that takes a CancellationToken, just a time span.
**The location request has a time span to auto cancel, you can cancel your self with the token**
c) The code snippet following the above recommendation does not do what the recommendation says, as it is lacking any kind of timeout.
** I will update the doc**
d) It is unclear what happens when the timeout is triggered -- will it return null, or will it return some kind of 'best match'?
**It will return best matched if found, else null**
e) Assuming some kind of location will be returned even with a short timeout, what kind of ballpark figure for timeout would be in any way acceptable?
**every device is different and every app is different, in my personal apps I use 5 seconds**

**Comment by Tommigun1980** [comment]
> Answers inline:
> On LastKnownLocationsAsync()
> a) In what scenario can a 'no cached location exist'? Is this a frequent occurrence?
> **A specific API is called on each platform to get the cached location. The OS is in charge of it. on Android we call GetLastKnownLocation, and iOS we check to see if CLLocationmanager has a location set, and on UWP we set AllowFallbackToConsentlessPositions**
> b) In regard to a), if returning null is a frequent occurrence, is the recommended pattern to first try to get a cached location, and if it fails do a real lookup?
> **This would be the recommended path, and also to check the timestamp**
> c) How often is this cached value updated, and under what conditions?
> **The OS decides, so a timestamp should be checked**
> d) Wherefrom does it draw the cached result? From a call to GetLocationAsync, or some internal update?
> **Internal**
> 
> On LocationAsync()
> a) What does passing in "a full GeolocationRequest" mean?
> **You can send in parameters to specify the request**
> b) There is no overload that takes a CancellationToken, just a time span.
> **The location request has a time span to auto cancel, you can cancel your self with the token**
> c) The code snippet following the above recommendation does not do what the recommendation says, as it is lacking any kind of timeout.
> ** I will update the doc**
> d) It is unclear what happens when the timeout is triggered -- will it return null, or will it return some kind of 'best match'?
> **It will return best matched if found, else null**
> e) Assuming some kind of location will be returned even with a short timeout, what kind of ballpark figure for timeout would be in any way acceptable?
> **every device is different and every app is different, in my personal apps I use 5 seconds**

Thank you so much for the answers, I really appreciate it!

Regarding 2b, iirc there is no overload that acceptance a cancellation token. Which token are you referring to?

Thanks again.

**Comment by jamesmontemagno** [comment]
The GetLocationAsync takes it in see the new docs https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=android#using-geolocation

**Comment by Tommigun1980** [comment]
> The GetLocationAsync takes it in see the new docs https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=android#using-geolocation

Thanks! Perfect!!
