### ISSUE TITLE
Extend document regarding using  Source property

### ISSUE THREAD

**Issue by EmilAlipiev** [MicrosoftDocs/xamarin-docs#2865]
Using Source property vs creating instance with cs code behind has totally different behavior. Please see the more information here on this[ SO question
](https://stackoverflow.com/questions/61980498/xamarin-forms-stand-alone-resource-dictionaries-dont-update-dynamically-if-ther)

this needs to be clearly stated in the documentation for those want to use this cool feature but there is a disadvantage in behavior. 

Beside that Document doesn't mention how to preserve on release build if full linker is used. Those resourcedictionaries without cs code behind will be removed by the linker and since it doesnt have any cs code file, how to Preserve it in Xaml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Xamarin.Forms resource dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @EmilAlipiev 

Apologies for the delayed response to your issue. I've made the sample (which the doc links to) linker safe. Therefore, the `ResourceDictionary` without a code-behind file is now preserved by the linker in release mode. I'll also update the doc this week.

**Comment by davidbritch** [comment]
I've looked at your issue in the linked SO post. Unless I'm misunderstanding something, I can find no issue here.

Given `<Color x:Key="NormalTextColor">Black</Color>` in the App.xaml resource dictionary, I added code to change the colour to red at runtime (in response to a button click): `Application.Current.Resources["NormalTextColor"] = Color.Red;`

Given MyResourceDictionary.xaml (XAML-only resource dictionary), which is consumed by a page as follows: `<ResourceDictionary Source="MyResourceDictionary.xaml" />`, when `NormalTextColor` changes to red at runtime, the resulting items remain black:

![Simulator Screen Shot - iPhone 11 - 2020-11-10 at 14 39 42](https://user-images.githubusercontent.com/8092460/98692049-9b0eb200-2366-11eb-8ecf-086e8e60e6e7.png)

This is because the `Label` objects consume the resource using the `StaticResource` markup extension:

```
<Label Text="{Binding Name}"
                       TextColor="{StaticResource NormalTextColor}"
                       FontAttributes="Bold" />
```

Switching the `Label` objects to consume the resource using the `DynamicResource` markup extension results in their colours changing to red (following the runtime change):

![Simulator Screen Shot - iPhone 11 - 2020-11-10 at 14 40 27](https://user-images.githubusercontent.com/8092460/98692159-b7aaea00-2366-11eb-8f33-f77131022394.png)

The behaviour is the same even if the contents of `MyResourceDictionary.xaml` are moved into a page-level resource dictionary on the consuming page - the colour is only updated if consumed as a `DynamicResource`. Not only is this the actual behaviour, it's the expected behaviour.

There could be multiple reasons why you received a different behaviour back in May. Regardless, I can't see a problem now. Let me know if you disagree.
