### ISSUE TITLE
Better example needed on how to call webapi once signed in.

### ISSUE THREAD

**Issue by Flexman** [MicrosoftDocs/xamarin-docs#2866]
The sample code provided works as in it will sign in using the provider authentication.

What the sample doesn't show is how to utilize the returned access token for subsequent calls to the webapi.

Adding as an authorization header as bearer with the access token results in a 401 on the webapi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
Giving to @redth

**Comment by jamesmontemagno** [comment]
@redth are we able to provide a sample of how to call the backend API authenticated?

Ideally you are jusst doing this:

```csharp
_httpClient.DefaultRequestHeaders.Authorization
    = new AuthenticationHeaderValue("Bearer", _loginResult?.AccessToken ?? string.Empty);
```

And then you check your bearer token on the backend:
https://stackoverflow.com/questions/25764732/retrieve-bearer-token-in-asp-net-webapi

**Comment by Redth** [comment]
The web api backend sample we have in Essentials demonstrates how to return the access tokens from the particular oauth service that the flow was initiated to.

What you're trying to do is call the web api itself as an authenticated client which you probably don't want to use the oauth provider access tokens for.  You're going to have to implement your own access token on your web api and send _that_ back to the callback as the access token instead of the token from the oauth provider.

Here's some sample code around generating tokens on your web api: https://github.com/davidfowl/Todos/tree/0809a99707c3856e722677a93de3d311451a9deb/TodoWithControllersAuthJWT
