### ISSUE TITLE
device-orientation.md Is one big link on the official docs website

### ISSUE THREAD

**Issue by JelleInfinity** [MicrosoftDocs/xamarin-docs#2887]
### Doc issue description

The [official forms page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation) seems to be outdated.

The link at **Responsive Layout** is not closed, even though it seems closed (couldn't find the issue) in the github source file.

**Comment by davidbritch** [comment]
Hi @JelleInfinity 


Thanks for reporting this. A change in the version of markdig used by the docs build system resulted in docs with HTML anchors incorrectly rendering with entire sections of text being hyperlinked.

The fix was to:

- Remove the 196 HTML anchors present in the Xamarin.Forms docs.
- Update the 204 impacted bookmarks to use the auto generated anchors.

Everything is now fixed for the Xamarin.Forms docs.
