### ISSUE TITLE
Half the page is in <a> tag

### ISSUE THREAD

**Issue by rozman50** [MicrosoftDocs/xamarin-docs#2898]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b708ef67-2a65-558b-7dc9-5df5a222dfd4
* Version Independent ID: df2f7e71-aa4b-dbb6-1d54-4f9b75ad8177
* Content: [Customizing an Entry - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/entry)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/entry.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/entry.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rozman50 


Thanks for reporting this. A change in the version of markdig used by the docs build system resulted in docs with HTML anchors incorrectly rendering with entire sections of text being hyperlinked.

The fix was to:

- Remove the 196 HTML anchors present in the Xamarin.Forms docs.
- Update the 204 impacted bookmarks to use the auto generated anchors.

Everything is now fixed for the Xamarin.Forms docs.
