### ISSUE TITLE
Unclosed link tag somewhere.

### ISSUE THREAD

**Issue by arrayofletters** [MicrosoftDocs/xamarin-docs#2909]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20276a4d-19f7-af3c-d38d-81f1dd8f0606
* Version Independent ID: 96e26460-4cfe-d7ef-3933-b2feb95a048e
* Content: [DataPages Controls Reference - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datapages/controls)
* Content Source: [docs/xamarin-forms/user-interface/datapages/controls.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/datapages/controls.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @arrayofletters 

Thanks for reporting this. A change in the version of markdig used by the docs build system resulted in docs with HTML anchors incorrectly rendering with entire sections of text being hyperlinked.

The fix was to:

- Remove the 196 HTML anchors present in the Xamarin.Forms docs.
- Update the 204 impacted bookmarks to use the auto generated anchors.

Everything is now fixed for the Xamarin.Forms docs.
