### ISSUE TITLE
We need to Add two important butt missing Layouts here:

### ISSUE THREAD

**Issue by BicycleMark** [MicrosoftDocs/xamarin-docs#2955]
[Enter feedback here]
We need to Add BindableLayout and sample [](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts)
We need to Add CollectionView 
[](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b7fe9d-eda5-ea03-1f95-b2ddcea26ec5
* Version Independent ID: 3c89f3d3-65f3-08d7-f0a4-bce5442221a8
* Content: [Xamarin.Forms Layouts - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/layouts)
* Content Source: [docs/xamarin-forms/user-interface/controls/layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/controls/layouts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BicycleMark 

`CollectionView` ultimately derives from `View`, and so is a view rather than a layout. Therefore you'll find it listed at https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/controls/views#views-that-display-collections

`BindableLayout` technically isn't a layout, in that it doesn't derive from `Layout`. It's an extension that binds collections to existing `Layout` classes. Therefore it's not listed in the Layouts (Controls reference) page.
