### ISSUE TITLE
Change examples to use the system fonts OSes are actually using

### ISSUE THREAD

**Issue by lnaie** [MicrosoftDocs/xamarin-docs#2983]
Guys, this is not optimal.
Please provide examples with the fonts the OSes are actually using. If they use the best font, and the assumption is yes, I would like to use it as well.
Why do you think I need to see an example with Lobster font?!

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @lnaie 

Unfortunately, the only reliable way to use the same font cross-platform is to use a custom font (e.g. Lobster), which is why the doc shows this approach. 

This is because different platforms ship different fonts, and the presence of a font on a platform does not mean it's present in other versions of the platform, or even in other locales. In addition, there's no reliable way to enumerate the fonts available all platforms.
