### ISSUE TITLE
"FusedLocationProviderClient" does not exist in current context.

### ISSUE THREAD

**Issue by DesmondANIMUS** [MicrosoftDocs/xamarin-docs#303]
So, I'm using latest Visual Studio 2017 with all SDK's updated. And I've made sure that I've installed GooglePlayServices(all of them). But for some reason, I'm not able to access this class. I am not sure why I tried looking around but haven't been able to find any solution yet. I thought it was because maybe I didn't have the AppCompatActivity, so I installed that as well. But I still cannot access this class.

Some help will be really appreciated. 

Thanks ^.^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091d4a3-b105-70f5-38d2-5b2de109ed04
* Version Independent ID: 7081d0bd-9061-eda8-dac2-1f6f42bffd02
* Content: [Location Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/location)
* Content Source: [docs/android/platform/maps-and-location/location.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/location.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @DesmondANIMUS, thanks for the feedback!  Unfortunately, the topic fails to mention which `using` statement you need in order to access this class -- we'll fix that soon. Meanwhile, be sure to add `using Android.Gms.Location;` to your source file. Also, you can have a look at the sample code linked at the end of the topic: https://developer.xamarin.com/samples/FusedLocationProvider/.
