### ISSUE TITLE
Issue with Android 10 API 29

### ISSUE THREAD

**Issue by AldairOrta** [MicrosoftDocs/xamarin-docs#3061]
[Enter feedback here]

As I'm working with external storage for my App and Write and Read files. The issue comes when I target API 29 (Android 10) and the App crashes because access is denied even tho the user to this step granted permissions. But when I downgrade API level to 28 (Android 9) the App just works fine. Is there a new storage thing I must know ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0297c8ec-f20a-6e75-91f0-15e3eaa17e02
* Version Independent ID: e2be85c7-bd3c-ec8a-837f-b8784dc2b3c6
* Content: [File access on external storage with Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/files/external-storage?tabs=macos)
* Content Source: [docs/android/platform/files/external-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/files/external-storage.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by AldairOrta** [comment]
The specific code error on API 29 is by calling "WriteAllBytes".

`File.WriteAllBytes(pathFile, myResultado);`

Where pahtFile is: "/storage/emulated/0/" + "DocumentNameThatChanges" + ".pdf"

And "myResultado" is the byte array I get from my web service

**Comment by davidbritch** [comment]
Hi @AldairOrta 

Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Other channels you can use to seek help include [Developer Community](https://developercommunity.visualstudio.com/), the [Xamarin Forums](https://forums.xamarin.com/), and [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin).
