### ISSUE TITLE
Xamarin tools  are not shown in activity_main.xml

### ISSUE THREAD

**Issue by hosamalhemmali** [MicrosoftDocs/xamarin-docs#3079]
I downloaded Visual Studio 2017 and when I opened the Xamarin
When I put tools such as text box or button and other tools, they do not appear in the screen or activity_main.xml
There is a written alert this project contains resources that were not complied
![xxxx](https://user-images.githubusercontent.com/71670727/93820158-9acd2280-fc11-11ea-9874-4bbc920a0222.png)

**Comment by davidbritch** [comment]
Hi @hosamalhemmali 

Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Other channels you can use to seek help include [Developer Community](https://developercommunity.visualstudio.com/), the [Xamarin Forums](https://forums.xamarin.com/), and [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin).
