### ISSUE TITLE
"Add-in Manager" is now "Extension Manager"

### ISSUE THREAD

**Issue by richardlawler** [MicrosoftDocs/xamarin-docs#31]
The installing CocosSharp section says to use the "Add-in Manager", but this doesn't seem to exist any more. The Extension Manager doesn't find the CocosSharp ad-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b14e35-4b8c-95e3-3552-1e81d3933b09
* Version Independent ID: fe72a978-d48f-8da1-0289-18ebec44135d
* Content: [Creating a Multi-Platform CocosSharp Project - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/graphics-games/cocossharp/first-game/part1)
* Content Source: [docs/graphics-games/cocossharp/first-game/part1.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/cocossharp/first-game/part1.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by bradumbaugh** [comment]
Hi @richardlawler. Thanks for calling this out. I'll provide an update for this doc!

**Comment by bradumbaugh** [comment]
Hi @richardlawler, I've updated and reorganized these docs a bit to remove the parts that reference the templates, since they are no longer available. I'd suggest opening an existing project (take a look at BouncingGame) to understand the project structure, references, etc. Thanks for calling this out!
