### ISSUE TITLE
Google Maps Android API Not Listed.

### ISSUE THREAD

**Issue by pw3107** [MicrosoftDocs/xamarin-docs#314]
'Google Maps Android API' is not listed when I log into my Google Developer Console? 'Maps SDK for Android' is listed with 16 other API's. Any idea's where to find it?
Thanks
Paul.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1bc9be-4365-8015-1c11-a9ab1770ea01
* Version Independent ID: 82abd821-8fe1-4204-be15-bf3d8a92abd7
* Content: [Obtaining a Google Maps API Key - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key?tabs=vswin)
* Content Source: [docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @pw3107, the Google Console has changed since this topic was written -- I've added a task to our backlog to research their changes and update this section of our doc so that it is in sync with Google. Until then, perhaps this [topic](https://developers.google.com/maps/documentation/android-sdk/signup#detailed-guides) will be of some help. Thanks for the feedback!
