### ISSUE TITLE
How to work when Android app closed

### ISSUE THREAD

**Issue by HUBBER12** [MicrosoftDocs/xamarin-docs#3151]
Many, including myself, have problems getting the android notifications to work while the app is asleep (active or background works great).  Since this seems to be very common complaint, can you first tell me what i might need to do to get it to work while app is asleep.  And second.. could you possibly devote a title and section on this page to this subject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by HUBBER12** [comment]
One thing i'm thinking as i look around for help... is that i just noticed that i need to be using AndroidX.. i guess i missed that wave.. and just now realized it... so i swapped out all my Nugets to AndroidX nugets instead of Android.Support.****  nuget packages.  I'm thinking that is a main reason why for everyone else this 'just works' and mine has issues when app is closed.  

So i'm not positive that is a fix it would seem like a good idea.  
i put it as target framework 10 instead of target framework 9.  And Xamarin Forms versino is 4.8.xxxx  
However i'm getting this one error, and cant find what Nuget Packages is still referencing   Xamarin.Support..****** 

**Assembly 'Xamarin.Android.Support.v4' is using '[assembly: Java.Interop.JavaLibraryReferenceAttribute]', which is no longer supported. Use a newer version of this NuGet package or notify the library author**

If this works then maybe add it to the documentation ( need  to be using Xamarin.AndroidX nugets over Xamarin.Support   + Xamarin.Forms version 4.5 or greater, and Android Target Framework 10+).  Again not sure if this is the case but i would think it would make sense why it's not 'just working' when app is closed - after following documentation when it works for others.

**Comment by davidbritch** [comment]
Hi @HUBBER12 

It makes sense that AndroidX is now required. The requirements on Google Play is that new apps must target AndroidX (or higher), and from last week app updates also have to target AndroidX or higher (see https://developer.android.com/distribute/best-practices/develop/target-sdk). Because of that, any bug fixes to Xamarin libraries will only be made in AndroidX packages. In addition, Xamarin.Forms 5.0 (the next release) requires the use of AndroidX.

Re: the Xamarin support library that's still being found. If the package isn't directly installed in your project, it'll be the case that a package in your project has a dependency on Xamarin.Android.Support.v4. So you either need to eliminate that dependency, or perhaps you could try relying on [AndroidX migration](https://docs.microsoft.com/xamarin/xamarin-forms/platform/android/androidx-migration) instead.

I'll get something added to the doc about requiring AndroidX.

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live later this week.
