### ISSUE TITLE
Bookmark transparent statusbar in shell and visible navigationbar

### ISSUE THREAD

**Issue by hamidish** [MicrosoftDocs/xamarin-docs#3164]
[Enter feedback here]

hi 
i want transparent statusbar in shell
 and i use this flag in mainactivity 
 Window.AddFlags(WindowManagerFlags.TranslucentStatus);
but when use only this flag transparent only work for contentpage not for shell page
but when use this flag too
            Window.AddFlags(WindowManagerFlags.LayoutNoLimits);
work in shell
but navigatinbar in bottom is invisible and when click in tabbar app goes onresume.

how can fix it?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hamidish 

Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Other channels you can use to seek help include [Developer Community](https://developercommunity.visualstudio.com/), the [Xamarin Forums](https://forums.xamarin.com/), and [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin).
