### ISSUE TITLE
Does Device.SetFlags still exists?

### ISSUE THREAD

**Issue by patrickhacens** [MicrosoftDocs/xamarin-docs#3195]
Device.SetFlags has the [EditorBrowsable(EditorBrowsableState.Never)] Attribute setted
Does Device.SetFlags still works? And if so should we update this information on docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5584d254-7331-a768-39d2-54d5a6f1e923
* Version Independent ID: a4ba858e-91f4-f79a-219e-6af8f6146fab
* Content: [Xamarin.Forms experimental flags - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags)
* Content Source: [docs/xamarin-forms/internals/experimental-flags.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/internals/experimental-flags.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @patrickhacens 

Yes, it works. It should never have crept into the docs, because of its attribute that stops it appearing in intellisense. However, it crept into official Microsoft blog posts which opened the doors to it appearing in the docs.

At this stage I don't propose removing it from the docs for two reasons:

1. Setting the flag in the .NET Standard library is a nicer approach than having to do it in each platform project.
2. All but one experimental flag has been removed in Xamarin.Forms 5.0, so the majority of people won't have any reason for setting an experimental flag.
