### ISSUE TITLE
Docs say set shape property `Stroke` to a `Color`, but I get a compiler error when using StaticResource.

### ISSUE THREAD

**Issue by eli-crow** [MicrosoftDocs/xamarin-docs#3234]
Docs say set Shape property's `Stroke` to a `Color`, but I get a compiler error when supplying a  `StaticResource` that is a `Color`.

Example code
``` xml
<!-- In some ResourceDictionary -->
<Color x:Key="BorderGray"/>
```

``` xml
<Line X1="0" X2="200" Y1="100" y2="100" Stroke="{StaticResource BorderGray}" />
```

The error: ` <MyApp>\Controls\DenseBarGraph.xaml:657 Invalid resource type: expected type is 'Brush', actual type is 'Color'.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 280a676e-d5b3-9e38-e71b-cea7cbc64659
* Version Independent ID: 3763152f-4af9-72d1-4d5a-3a59a19c31ac
* Content: [Xamarin.Forms Shapes: Line - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/line)
* Content Source: [docs/xamarin-forms/user-interface/shapes/line.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/shapes/line.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli-crow 

It was a `Color` but now it's a `Brush`. I'll get it updated today.

**Comment by davidbritch** [comment]
Working through this issue. So the [Shapes page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/) tells us that `Stroke` is of type `Brush`, which is correct.

Then the [Line page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/line) tells us that `Stroke` can be set to a `Color`, which is also correct:

```
            <Line X1="40"
                  Y1="0"
                  X2="0"
                  Y2="120"
                  Stroke="Red" />
```

The above code works because there's a converter that's automatically run on the `Stroke` property, which converts the `Color` value to a `SolidColorBrush` (which derives from `Brush`).

The problem seems to be that the moment you switch to using a `Color` defined as a `StaticResource`:

```        <Color x:Key="myColor">Red</Color>

            <Line Stroke="{StaticResource myColor}"
                  StrokeThickness="5"
                  X1="40"
                  Y1="0"
                  X2="0"
                  Y2="120" />
```

The above code does build for me (I'm using VSMac), but it also doesn't draw a line when I run it.

So I updated the resource to be a `SolidColorBrush`:

```
  <SolidColorBrush x:Key="myColor" Color="Red" />
  
            <Line Stroke="{StaticResource myColor}"
                  StrokeThickness="5"
                  X1="40"
                  Y1="0"
                  X2="0"
                  Y2="120" />
```

This builds, runs, and draws the red line. So ultimately that's the solution.

Obviously the docs require an update to clarify this. I'll get on it.
