### ISSUE TITLE
Async calls for Data Manipulation functions not used?

### ISSUE THREAD

**Issue by zishani** [MicrosoftDocs/xamarin-docs#3241]
Under the Data Manipulation section, you show code samples like so for retrieving data:

```
    public Task<List<TodoItem>> GetItemsAsync()
    {
        return Database.Table<TodoItem>().ToListAsync();
    }
```

However should these code samples not be asynchronus like this:

```
    public async Task<List<TodoItem>> GetItemsAsync()
    {
        return await Database.Table<TodoItem>().ToListAsync().ConfigureAwait(false);  
    }

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @zishani 

The method with async/await wraps the execution of the inner task in an outer compiler-generated task. The non-async version does not, and so is marginally more efficient.

The general rule of thumb is: methods declared as `async` and using `await` are converted into a state machine by the compiler. So when you hit the `await` the control flow is returned to the calling method and execution of your `async` method return is resumed after the `await` when the awaited `Task` has finished. Because there's no more code after your `await`, there's no need to use `await` anyway. Returning the `Task` is enough.
