### ISSUE TITLE
FontAwesome and Glyphs don't seem to work ...

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/xamarin-docs#3255]
I have imported the font like so 
`[assembly: ExportFont("FontAwesome5Pro_Light_300.otf", Alias = "FA5Light300")]`

I have a font and it's set to "Embedded Resource"
![image](https://user-images.githubusercontent.com/12648793/109736446-51a2d680-7b92-11eb-90e1-e6cb8424a063.png)

In my XAML for the AppShell.xaml I have this ...
![image](https://user-images.githubusercontent.com/12648793/109736520-75661c80-7b92-11eb-8d3f-8c99dbfb8de2.png)

This uses a namespace to point to the string value for "Sync" contained in FA5ProLight300.cs
xmlns:fontAwesome="clr-namespace:XXXamarin.Fonts;assembly=XXXamarin"
fontAwesome:FA5ProLight300.Sync

I have even tried the escaped value and that doesn't work ether ....

No glyph appears ..
No XAML binding errors
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by stephenhauck** [comment]
Also just noticed .. I am running Visual Studio 2019 on WIndows with MFractor and it decodes things properly while running and I put my pointer over it in the XAML ...
![image](https://user-images.githubusercontent.com/12648793/109737594-4f417c00-7b94-11eb-8dc8-23d48db3a7bd.png)

**Comment by stephenhauck** [comment]
Forgot to mention I am running Xamarin Forms 5.0.0.2012+671-sha.68c17772d-azdo.4465181

**Comment by stephenhauck** [comment]
Bump ... anyone ...

**Comment by stephenhauck** [comment]
If we are "exporting the fonts" in the shared code like so ...
`[assembly: ExportFont("FontAwesome5Pro_Light_300.otf", Alias = "FA5Light300")]`

Why would people include the fonts for each platform like so when the fonts are not platform dependent ?

**Comment by davidbritch** [comment]
Hi @stephenhauck 

Lots of people have had issues with FontAwesome, but  but their fixes have all been different. See https://github.com/xamarin/Xamarin.Forms/issues?q=is%3Aissue+fontawesome+is%3Aclosed+ and https://github.com/xamarin/Xamarin.Forms/issues?q=is%3Aissue+font+awesome+is%3Aclosed+ for some suggested fixes.

As it's an issue with the product, rather than the docs, the recommended place to seek help is the [Xamarin.Forms channel](https://docs.microsoft.com/en-us/answers/topics/dotnet-xamarinforms.html) on Microsoft Q&A.

> Why would people include the fonts for each platform like so when the fonts are not platform dependent ?

Prior to the `ExportFont` attribute being available, the only option was to include font files in each platform project, with additional platform project setup. However, the `ExportFont` attribute removes the need to add font files to platform projects (and no need for platform config either)./
