### ISSUE TITLE
Startup dual screen missing in doc.

### ISSUE THREAD

**Issue by KimmoLiukkonen** [MicrosoftDocs/xamarin-docs#3272]
Hello and thank you for good and clear document.
I have Xamarin Forms project and TwoPaneView (Surface Duo Emulator) works fine...almost!
There is no example how to start app in dual screen mode (Spanned to both screens). I always have to drag window from that black bottom line to split app in two screen.

-Kimmo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab320334-40cb-ecde-2b5f-334f12a1203e
* Version Independent ID: f5ad593c-8e4e-b3ed-2543-f96aa788c0eb
* Content: [Xamarin.Forms Dual-Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dual-screen/)
* Content Source: [docs/xamarin-forms/app-fundamentals/dual-screen/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dual-screen/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Hi @KimmoLiukkonen, 

There is no way to force an app to open spanned - apps will always open on one screen, and the user can then drag the app to be spanned.

This is by design, so that the user doesn't get surprised by apps behaving differently.

We recommend using a first-run-experience or some other hints to let your users know that they should span!
