### ISSUE TITLE
DropCompletedEventArgs missing DropResult property

### ISSUE THREAD

**Issue by figa1993** [MicrosoftDocs/xamarin-docs#3302]
DropCompletedEventArgs is documented on this page as having a DropResult property, but this is inconsistent with the information in https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.dropcompletedeventargs?view=xamarin-forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07c1436-d8cf-8f5e-939b-3da68122f83e
* Version Independent ID: ba4d582d-447d-017c-7b36-d18357e83187
* Content: [Add drag and drop gesture recognizers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/drag-and-drop#handle-the-dragover-event)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @figa1993 

Agreed that you are correct. I'll get the doc updated today. Interestingly, the [source](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/DragAndDrop/DropCompletedEventArgs.cs) shows a `DropResult` field, that turns out to be unreferenced throughout the entire codebase.
