### ISSUE TITLE
Clarification on Android Xamarin Essentials docs

### ISSUE THREAD

**Issue by benwalpole** [MicrosoftDocs/xamarin-docs#3429]
The sentence here around when Essentials needs to be initialised on Android could be clearer:

"In the Android project's MainLauncher or any Activity that is launched, Xamarin.Essentials must be initialised in the OnCreate method:"

Is this saying Essentials needs to be initialised in every activity in the app or only one or just in the MainLauncher? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Get Started with Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?context=xamarin%2Fandroid&tabs=macos%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
It will need to be initialized in just the MainLauncher. It tracks new activities started and stopping. However, if you have the ability to start another Activity independently from the MainLauncher then you should initialize it there too. 

You can also call `Init` with a custom `Application` instead of the `Activity`
