### ISSUE TITLE
The page about AOT limitations should talk about the interpreter

### ISSUE THREAD

**Issue by rolfbjarne** [MicrosoftDocs/xamarin-docs#3546]
The page about AOT limitations:

https://learn.microsoft.com/en-us/xamarin/ios/internals/limitations

should talk about how enabling the interpreter might solve many (most? all?) of these scenarios that aren't supported when just using the AOT compiler.

Note that the exception app developers get when running into any AOT limitation points to that page, so it's rather important that it contains helpful information:

>  System.ExecutionEngineException: Attempting to JIT compile method ... while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

(from https://github.com/dotnet/runtime/issues/69410)

**Comment by projectgoav** [comment]
I'd like to add my voice to this and potentially up the priority a bit. 

I encountered this issue on all configurations when deploying app on a physical device. As this didn't happen with Xamarin.iOS but does under the new toolchain 

I'd be useful to have all the information linked at the page the compiler points you towards rather than having to trawl many Github issues across a number of repos. At the very least, a pointer towards some of the discussions on Github would be a step forward.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
