### ISSUE TITLE
"Build the project to create the IPA package"

### ISSUE THREAD

**Issue by EtienneJuneau** [MicrosoftDocs/xamarin-docs#367]
Maybe this is too much of a newbie question, but when you write "Build the project to create the IPA package", what do you have in mind? Should I build using the green arrow/button in the debug toolbar, or using the build menu?

I'm stuck and can't build the IPA. I wonder if this step is the problem. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin#building-and-submitting-the-distributable)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @EtienneJuneau, after configuring the project properties to build the ipa file (make sure to – for the correct build configuration – actually select the checkbox next to **Build iTunes Package Archive (IPA)** on the **iOS IPA Options** tab), select the correct build configuration and build the solution. Since in this scenario you don't want to run/debug, I would just use the build option from the **Build** menu.

I'll update the doc to call out that you need to actually select that checkbox for building the IPA file.

If this doesn't solve your problem, please feel free to post a question on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
