### ISSUE TITLE
Need to update this documentation

### ISSUE THREAD

**Issue by sfoxover** [MicrosoftDocs/xamarin-docs#377]
You need to update the documentation with how to install Google Android emulator package 27.2.7.  The preview has 27.1.12. You need to document how to install the alpha build in Visual Studio Preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by sfoxover** [comment]
This is the link I was after:
http://aka.ms/hyperv-emulator-dl

From this page:
https://blogs.msdn.microsoft.com/visualstudio/2018/05/08/hyper-v-android-emulator-support/

**Comment by mgmclemore** [comment]
Hi @sfoxover, thanks for the feedback!   As of Visual Studio 15.8 Preview 1 (see step 3 of the [Hyper-V](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin#hyper-v) section), you no longer have to explicitly install the Xamarin.VisualStudio VSIX mentioned in the blog post because that functionality is now built into the latest Visual Studio Previews. Step 4 explains how to install emulator package 27.2.7.

**Comment by sfoxover** [comment]
I am using Visual Studio Professional 2017 Preview version 15.8.0 Preview 2.0. For some reason I was stuck on 27.1.12 until I installed the VSIX, Then it gave me an upgrade available in the dialog. I did not do a fresh install of Visual Studio 2017 Preview. Perhaps a fresh install would have also fixed the issue.

**Comment by mgmclemore** [comment]
Hmm, that sounds like a possible regression. I'll add your tip to install the VSIX as a workaround until this gets sorted out. Thanks again!

**Comment by mgmclemore** [comment]
Addition should be published soon.
