### ISSUE TITLE
Running as administrator

### ISSUE THREAD

**Issue by hubertdej** [MicrosoftDocs/xamarin-docs#38]
AVDs aren't visible in Visual Studio because they are located inside "Users\Admin\\.android\avd" folder rather than user specific one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77921f62-3d69-ff6e-57a8-ebe4bffde990
* Version Independent ID: d12d0c6d-5e03-533e-a6cc-fe940ff18206
* Content: [Xamarin Android Device Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/xamarin-device-manager?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/xamarin-device-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/xamarin-device-manager.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
@hubertdej, thank you for taking the time to provide feedback!  The screenshot in that topic showing a user-specific location for the AVDs was taken while running as administrator (Visual Studio version 15.6.0). If you are unable to see AVDs when clicking **Reveal in Explorer**, it could be that you have hit a bug. Could you please create an issue at https://developercommunity.visualstudio.com/ so the product team can take a look at it?  Thanks you!

**Comment by hubertdej** [comment]
@mgmclemore  That's not the case.
**Reveal in Explorer** works, it points to "_C:\users\Admin\\.android\avd_" where all the files are. The problem is that AVDs aren't listed here:

![](https://i.imgur.com/xaZR6yl.png "Screenshot")

Copying files from "_C:\users\Admin\\.android\avd_" to "_C:\users\\{CURRENT USER}\\.android\avd_" makes AVDs appear in the list. When I launch an emulator from there, [quick boot](https://blog.xamarin.com/android-emulator-quick-boot/) doesn't work (I guess that's what administrator privileges are required for).

**Comment by mgmclemore** [comment]
Ah, my misunderstanding. Still, it looks as though you have hit a bug that we are unable to repro on this end. If you create an AVD, it should appear in the device list, and it should not be necessary to manually copy over AVD files in order to get them to show up there. Can you provide the following information to help us repro the problem?

1. Are you logging in as  Administrator or logging in as a user?
2. When you installed Visual Studio, did you install while logged in as a user or Administrator?
3. Can you provide the version of Visual Studio you are running (click **Help > About Microsoft Visual Studio**).

Thanks in advance!
