### ISSUE TITLE
Facing issue on creating static library

### ISSUE THREAD

**Issue by ananthasivanvk** [MicrosoftDocs/xamarin-docs#482]
Hello,

I am getting the following error message while trying to execute the make command,
"No rule to make target `-project', needed by `libColorPicker-i386.a'.  Stop."

I could see some posts in Xamarin forum : https://forums.xamarin.com/discussion/92490/no-rule-to-make-target

and in stack overflow as well :  https://stackoverflow.com/questions/39493647/no-rule-to-make-target-project#comment89073863_39493647

for the above mentioned issue.

But couldn't get any resolution so far. Could you please let me know what is that I am doing wrong here?

Regards
Anand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c37f6af1-e697-321a-a3ac-077446a8a3fe
* Version Independent ID: f3e6b4c1-6910-f7ec-6f3b-0d3709ce2a82
* Content: [Walkthrough: Binding an iOS Objective-C Library - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/walkthrough?tabs=vsmac#feedback)
* Content Source: [docs/ios/platform/binding-objective-c/walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/binding-objective-c/walkthrough.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @ananthasivanvk, I ran through this doc up to the `make` command in the **Creating a Fat Binary** section, and it built as expected. A couple of things I'd suggest:

- Please be sure that you have installed the Xcode command-line tools (using the `xcode-select --install` command, as described in the doc)
- I did update my **Makefile** a bit, removing the 32-bit project types. My **Makefile** now reads as follows, and is in the same directory as the **InfColorPicker** directory that I've used to create the static library project (as described in the doc):

```
XBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
PROJECT_ROOT=./InfColorPicker
PROJECT=$(PROJECT_ROOT)/InfColorPicker.xcodeproj
TARGET=InfColorPicker

all: lib$(TARGET).a

lib$(TARGET)-i386.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphonesimulator -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphonesimulator/lib$(TARGET).a $@

lib$(TARGET)-arm64.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphoneos -arch arm64 -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphoneos/lib$(TARGET).a $@

lib$(TARGET).a: lib$(TARGET)-i386.a lib$(TARGET)-arm64.a
	xcrun -sdk iphoneos lipo -create -output $@ $^

clean:
	-rm -f *.a *.dll
```

I'll add a note to our internal backlog to review this doc for accuracy as a whole, including the 32-bit references in the **Makefile** (and elsewhere).

However, since I was able to build the static library by following the steps in the doc, I'm going to close this issue. That said, if you need support please feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by ananthasivanvk** [comment]
Hey Brad

Thanks a lot, I am able to create the static library by copying your modified makefile.

Regards
Anand

**Comment by vineetchoudhary** [comment]
I faced the same issue. I've created a script for same

```
#xcodebuild location
XBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

#Project root
PROJECT_ROOT=/Volumes/LongTime/Shared/RESideMenu/

#Complete Project Path
PROJECT=/Volumes/LongTime/Shared/RESideMenu/RESideMenu.xcodeproj

#Target Name
TARGET=RESideMenu


#build for i386 (iPhone Simulator)
${XBUILD} -project ${PROJECT} -target ${TARGET} -sdk iphonesimulator -configuration Release clean build
mv ${PROJECT_ROOT}/build/Release-iphonesimulator/lib${TARGET}.a ${PROJECT_ROOT}/lib${TARGET}-i386.a

#build for arm64.a (iPhone)
${XBUILD} -project ${PROJECT} -target ${TARGET} -sdk iphoneos -arch arm64 -configuration Release clean build
mv ${PROJECT_ROOT}/build/Release-iphoneos/lib${TARGET}.a $PROJECT_ROOT/lib${TARGET}-arm64.a

#build combine i386 and arm64
xcrun -sdk iphoneos lipo ${PROJECT_ROOT}/lib${TARGET}-i386.a ${PROJECT_ROOT}/lib${TARGET}-arm64.a -create -output ${PROJECT_ROOT}/lib${TARGET}.a

#Check arch
xcrun -sdk iphoneos lipo -info lib${TARGET}.a
```

https://gist.github.com/vineetchoudhary/f6d2dc82f16e68bd931a3e42ff264672
