### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PieterjanDeClippel** [MicrosoftDocs/xamarin-docs#49]
Java.Lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set android:windowActionBar to false in your theme to use a Toolbar instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077a373a-710a-4514-ba04-dee36309d7b3
* Version Independent ID: f8357c4d-8711-457a-3577-cce29464b51e
* Content: [Replacing the Action Bar - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/tool-bar/replacing-the-action-bar)
* Content Source: [docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
@PieterjanDeClippel, thanks for the feedback!  It works on Android 5.0 (current at the time it was written), but I get the same exception when running on Nougat. This topic needs to be updated for later versions of Android.

**Comment by mgmclemore** [comment]
Hi @PieterjanDeClippel, it turns out that I got the same exception because I accidentally overlooked the step of adding the custom `MyTheme` to `<application>`. When I followed the steps again carefully, everything worked as expected on later versions of Android (including Android 8.0). Can you check that your app is plugging in the custom theme?  In **AndroidManifest.xml**, `<application>` should have the following attribute:

```
android:theme="@style/MyTheme"
```

When that attribute is missing, I get exactly the error you report above. I've set off that important step in the topic so that it isn't so easily overlooked, and also added a Troubleshooting section that points out the exception and how to resolve it. Should be published soon.
