### ISSUE TITLE
Update from "PCL" to ".NET Standard" in text of "Creating Mobile Apps with Xamarin.Forms" Book

### ISSUE THREAD

**Issue by bjberger** [MicrosoftDocs/xamarin-docs#524]
Are there plans to update the text of "Creating Mobile Apps with Xamarin.Forms" to reflect the change from "Portable Class Libraries (PCL)" to ".NET Standard" as the "Code Sharing Strategy"?   I noticed that some or all of the code samples have already been updated.  How about the text of the book?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552cf4bf-553b-d7f4-adc6-7e696029c18b
* Version Independent ID: 67f96253-4908-3f85-fd2f-07563d1b4f7b
* Content: [Creating Mobile Apps with Xamarin.Forms Book First Edition - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/index)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
Updating the book is a big job and there are currently no plans to do it. We hope that the content of the book is still of value despite the anachronisms, and trust that much of our other Xamarin.Forms documentation can keep you up-to-date with the latest features.

**Comment by abrantie11z** [comment]
seriously Charles, please and please and please update this book ok. is the best i read. you see learning concept of programming in my opinion is not just presenting codes , but the way u explain the point , link to real world issues before you bring the code example makes your book very understanding and interesting to read.

**Comment by timmi4sa** [comment]
@charlespetzold Hi Charles, your name is near and dear to me ever since I got my hands on "C for Windows 3.1" (if I remember the title correctly) back in 1994! The create window class and message loop was so exciting (and hard to embrace). Today with the advent of Xamarin.Forms.Shell and new controls to support it makes it super hard to stay excited with Xamarin. Therefore an updated book would be an amazing resource for the .NET community, and your expertise is legendary!!! Please pitch this idea to the higher-ups for the sake of developers world wide (and of the greater good).

**Comment by pstricks-fans** [comment]
This book is very well suited for the beginners like me. Reading a book in which some parts are outdated seems to be hard for beginners.

I understand you might be very busy. I am so sorry. Why don't you delegate someone to update the contents maybe under your supervision thereby this book can still be easy to follow for the beginners and less confusing because of outdated parts.
