### ISSUE TITLE
MVVM approach is weird

### ISSUE THREAD

**Issue by r2d2rigo** [MicrosoftDocs/xamarin-docs#528]
Why is the sample using `static` members in the viewmodel? I have never seen this approach, even for simplification's sake, and it could be confusing to beginners. I think changing it to a regular viewmodel and instantiating a static copy somewhere, maybe in the own `ContentPage`'s resources, would be more beneficial since it shows how it is done more commonly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed970855-6db1-6838-12cf-5a6f58b8ebf4
* Version Independent ID: edfe1b4d-58d2-477d-89b2-2641789cf2db
* Content: [Part 5. From Data Bindings to MVVM - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm#implementing-a-navigation-menu)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
The `PageDataViewModel` class has only one static member. The `Title` and `Description` members used for binding on the `TextCell` in the XAML file are both instance members, as is the `Type` property accessed in the code-behind file.

The only static member is `All`, which is a collection of all the instances of `PageDataViewModel`. There is no reason for each of the instances of `PageDataViewModel` to have its own instance of this collection. That would be wasteful and awkward. That's why that `All` property is static and initialized in a static constructor.
