### ISSUE TITLE
Which viewController in ReceivedLocalNotification 

### ISSUE THREAD

**Issue by amalwankar** [MicrosoftDocs/xamarin-docs#530]
In the post above the ReceivedLocalNotification method uses a viewController to present the alert. But does not show how the viewController is initiated. I am assuming that the method is overridden in AppDelegate. Please correct me if I am wrong. Would appreciate any help. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0eb534-f7f4-e6c4-048f-d0712ebebe03
* Version Independent ID: 8aa5d675-3d41-492f-23fe-c11fb4e7efcf
* Content: [Notifications in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/deprecated/local-notifications-in-ios)
* Content Source: [docs/ios/platform/user-notifications/deprecated/local-notifications-in-ios.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/user-notifications/deprecated/local-notifications-in-ios.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @amalwankar – thanks for calling this out. Most docs have an associated code sample; in this case, you can [find it here](https://developer.xamarin.com/samples/monotouch/LocalNotifications/) to get more of a full context.

That said, it looks like the doc was somewhat different from the code, so I've updated the doc to match what's in the sample:

Instead of presenting with `viewController`, the code now reads like this:

```csharp
Window.RootViewController.PresentViewController(okayAlertController, true, null);
```

Thanks for calling this out – should be published soon. Appreciate your help in improving the docs!
