### ISSUE TITLE
Xamarin.Essentials Gelocation: No Altitude property to Location

### ISSUE THREAD

**Issue by djaus2** [MicrosoftDocs/xamarin-docs#533]
On the Geolocation page

https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android

 the example for getting the current location shows an error for **Altitude** property:

    var location = await Geolocation.GetLastKnownLocationAsync();

    if (location != null)
    {
        Console.WriteLine($"Latitude: {location.Latitude}, Longitude: {location.Longitude}, Altitude: {location.Altitude}");
    }

var alt = location.Altutude;

 shows a squiggly line under Altitude and message says the property is unknown. It suggests that it should be replaced with Lattitude!

PS: This is not a runtime issue of it being null. Its picked up by Intellisense.

**Comment by bradumbaugh** [comment]
Hi @djaus2, I tried the code in the docs using the latest version of Xamarin.Essentials (0.8.0-preview) on both iOS and Android (making sure to add location permissions in both cases), and everything worked as expected.  Since it appears the docs are correct, and this repository is for documentation-specific issues, I'm going to close this issue.

That said, please try updating to the latest version of Xamarin.Essentials and giving it another try. 

If that doesn't work, please feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) for support. Thank you!

**Comment by djaus2** [comment]
![noaltitude](https://user-images.githubusercontent.com/12537105/42743382-922bcd0a-8906-11e8-9063-550f340a401a.png)

No Altitude property.

**Comment by djaus2** [comment]
Glad both items were resolved. Thx.
