### ISSUE TITLE
Does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by Rhywden** [MicrosoftDocs/xamarin-docs#542]
I saw the closed feedback which promised a rewrite 2 months ago. This rewrite obviously didn't happen because the steps detailed here do not work for VS 2017. Yes, someone linked to parts of the "manual provisioning" but that does not work either simply due to the fact that if you do not subscribe to a paid account then you have no way of creating or downloading a provisioning profile - the provided link for doing so simply throws you back onto your main account page where the utmost you can download is Xcode.

Basically, I cannot select a provisioning profile. I can build and deploy projects from Xcode itself just fine.

Please, guys, if you write guides such as these - do try to actually create an account from which you follow your own steps. Or better yet: Get someone else who never touched Xamarin, and have them follow your guide.
You'll see pretty quickly that your guide still leaves a lot to be desired on the "not having to guess at what to do next" part.
And if you promise a rewrite then actually do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9b2b39-f572-75dc-f022-cada4919f129
* Version Independent ID: 804f0f6d-ed12-18d8-30b8-95b5aaa19d8a
* Content: [Free Provisioning for Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/free-provisioning)
* Content Source: [docs/ios/get-started/installation/device-provisioning/free-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/free-provisioning.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @Rhywden, I've taken a look at this doc and made a number of clarifications; updates should be published soon. I tested that the steps work on VS2017, too.

In the meantime, here's a broad-strokes outline:

- In Xcode's preferences, log in with your free Apple ID
- Create a new project in Xcode, setting it up with the same bundle identifier your Xamarin.iOS app will ultimately use (**com.yourname.yourapp** or something similar)
- Have Xcode automatically generate the necessary provisioning profiles for that bundle identifier; test it out by running the blank app in Xcode
- Switch over to Visual Studio 2017, and [pair it to the Mac](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/)
- Make sure your Xamarin.iOS app's bundle identifier matches the bundle identifier you used in blank app you created with Xcode
- In Visual Studio 2017, open your Xamarin.iOS project's **Properties**. 
- On the **iOS Bundle Signing** tab, use manual provisioning.
- Select the signing identity and provisioning profile Xcode created (which Visual Studio has access to since it is paired to the Mac).
- Build and deploy your app.

Hope this helps, but again – please keep an eye out for the updated doc. The PR is currently waiting for review.

Thanks!
