### ISSUE TITLE
MainActivity.cs contains reference to "myButton"

### ISSUE THREAD

**Issue by petemillermultimedia** [MicrosoftDocs/xamarin-docs#561]
In Visual Studio Community the MainActivity.cs contains two lines of code referencing a button, myButton, so at the point in the Android Quickstart tutorial immediately after pasting code into PhoneTranslator.cs (when it tells you to build), the build will fail.

**Comment by mgmclemore** [comment]
Hi @petemillermultimedia, the [quickstart](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vsmac) has this step (under **Wiring up the Interface**), which you may have missed:

_Remove the template button handling code so that the OnCreate method resembles the following:_

This removes the code referencing `myButton`. We'll update the quickstart to call this out more explicitly so that it is not accidentally overlooked. Thank you for your feedback!
