### ISSUE TITLE
Universal platform and IIS ASP.Net samples

### ISSUE THREAD

**Issue by Scherlac** [MicrosoftDocs/xamarin-docs#567]
Hi, I've also read about this technology on [xamarin](https://blog.xamarin.com/sharper-html-hybrid-apps-with-razor/) site. I think I'd give a try to experiment on this. Can you please give additional samples for UWP and ASP.Net platform on how to load site and catch the "hybrid:" requests. I'd like to see some template similar to the cross platform Xamarin template with shared project for models and etc. I think those app were later on easy to port to PWA (progressing web application). Nice document!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a22de7-13a8-13b4-a64e-8409fe7ffe13
* Version Independent ID: 43e8f786-c53e-beb4-15bb-1e23d50cf8c5
* Content: [Building HTML views using Razor Templates - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/razor-html-templates/)
* Content Source: [docs/cross-platform/platform/razor-html-templates/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/platform/razor-html-templates/index.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @Scherlac, I'm glad you found this doc to be helpful. It sounds to me like you're looking for help specifically with ASP.Net or Progressive Web Apps. Since these docs are Xamarin-specific, the best thing to do would be to leave a comment in the docs for one of those other areas. In particular, take a look at the [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio) and [Progressive web apps on Windows](https://docs.microsoft.com/microsoft-edge/progressive-web-apps) docs.
