### ISSUE TITLE
Outdated TestFlight documentation.

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/xamarin-docs#583]
iTunes Connect has changed its name to App Store connect. Also, all the screens are completely outdated. Testflight now looks completely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 191ddc6e-9887-70bd-b145-c0ab46c1f64f
* Version Independent ID: a190cb9e-0af1-60f9-41f1-b98282f7bce8
* Content: [Using TestFlight to Distribute Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/testflight?tabs=vsmac)
* Content Source: [docs/ios/deploy-test/testflight.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/testflight.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @Mikilll94 – thanks so much for calling it out, I appreciate it. I have an item in our backlog to update references to iTunes Connect everywhere, and I've added one to take a look at the TestFlight documentation as well. Going to close this since I'm tracking it internally. Thanks again for your help!
