### ISSUE TITLE
Not clear if it's possible to use resource values in e.g. BroadcastReceiver attributes

### ISSUE THREAD

**Issue by mungojam** [MicrosoftDocs/xamarin-docs#591]
I'd like to enable a receiver based on a resource boolean flag. This is possible with native 'AndroidManifest.xml', but it's not clear if it would be possible when using the Xamarin attributes to create the receiver. The resource just returns the id so it can't compile as a bool:

```    
[BroadcastReceiver(
        Label = "MyReceiver",
        Name = "MyReceiver.AppInstalled",
        Enabled = Resource.Boolean.beforeOreo
     )]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db71a47-f7c4-e619-af5d-f173d97df1bd
* Version Independent ID: 1f6af9fe-e53f-de92-041a-4340b1ae45a4
* Content: [Android Resource Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/android-resource-basics?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/resources-in-android/android-resource-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/android-resource-basics.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
I don't believe this is possible because the `BroadcastReceiverAttribute.Enabled`  is expecting a [boolean](https://developer.xamarin.com/api/property/Android.Content.BroadcastReceiverAttribute.Enabled/), and resource ID's are just an integer. There is no way for the Xamarin.Android build process to "map" the resource to the XML attribute that gets generated.

If you feel this is an important feature that is lacking, please raise an issue over at the [MS Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

As a workaround (I haven't tried this), but I suspect that you could skip the `BroadcastReceiverAttribute`  from the class, and manually register the BroadcastReceiver in the manifest yourself.
