### ISSUE TITLE
Is this article using images from Asset Catalogs

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#609]
Is this article using images from Asset Catalogs if not than how I will support all screen sizes for splash screen? I am following this article to create splash screen for iOS but there I can only set the launch screen to only 1 image, I want to make sure that it will be displayed the same across all devices. I have added all sizes required in the Asset Catalogs> Assets> LaunchImages

I set the Launch Screen to LaunchScreen in the Info.plist but the assets images are not available in the image drop-down list (only images in the same directory of the LaunchScreen.storyboard), so, the LaunchScreen dosn't have access to the assets folder of the Asset catalogs!

![asssests](https://user-images.githubusercontent.com/19743421/43504068-8f833bf8-957f-11e8-896e-7c8b975ff571.png)

**Comment by bradumbaugh** [comment]
Hi @arvindrajachourasiya, sorry to hear you've hit a snag.

As described in [this guide](https://docs.microsoft.com/xamarin/ios/app-fundamentals/images-icons/launch-screens?tabs=vsmac), you'll want to use a launch screen storyboard, rather than static images. A launch screen storyboard can be used to define a launch screen that looks good on all iOS devices.

If you add an image set to an asset catalog, those images should be available in your launch screen storyboard. Add an Image View to the view controller in the storyboard, select the image, open the **Properties Pad**, and set select the image the asset catalog in the **Image** drop-down list.

If this isn't working for you, feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
