### ISSUE TITLE
This solution worked for me

### ISSUE THREAD

**Issue by rgoudie** [MicrosoftDocs/xamarin-docs#682]
Yesterday, I updated my Visual Studio 2017 Community Edition to the latest version: 15.8.1.
I updated my NuGet packages upon loading my existing Xamarin project.
I then deleted all of the files in the Xamarin project's bin and obj folders in order to do a clean build.

During compilation, I received the javac exception: PathTooLongException.

I added &lt;UseShortFileNames&gt;True&lt;/UseShortFileNames&gt; to my Android project. This did not resolve the issue.
I added my version of &lt;IntermediateOutputPath&gt;C:\Projects\MyApp&lt;/IntermediateOutputPath&gt; to my Android project. This DID resolve the issue.

However, I must state that this exception only started appearing as of the latest version of Visual Studio 2017 Community Edition. Prior to the update (and for the past several months), I could compile my Xamarin project without seeing this exception.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500cca09-76fd-5df5-6bd9-90cc51fae84d
* Version Independent ID: 3a9bfdcc-ac3a-6cdf-ab20-9fc425c56b71
* Content: [How do I resolve a PathTooLongException error? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception)
* Content Source: [docs/android/troubleshooting/questions/path-too-long-exception.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/path-too-long-exception.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @rgoudie, thank you for the feedback!  Since `IntermediateOutputPath` is already covered in the topic, there is nothing more we can do with the documentation. However, you can click the **Product Feedback** button at the bottom of the topic page to describe your observations (this takes you to [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), where we gather bugs, issues, and feature suggestions for products). Thank you!
