### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by scastria** [MicrosoftDocs/xamarin-docs#683]
I was able to follow all of the SkiaSharp Transforms section until this one, "Touch Manipulations".  The reason is that Touch Manipulations examples have jumped too far ahead showing a lot of OOP encapsulation and good design.  I think we need a much simpler bad design example first that concentrates on 1 bitmap.  Basically, I would like to see single file examples, like all of the others have been, that shows how to:
1. drag a bitmap with 1 finger
2. same as previous AND add ability to scale a bitmap with 2 fingers (where scale pivot is center of 2 fingers)
3. same as previous AND add ability to rotate a bitmap with 2 fingers (where rotate pivot is center of 2 fingers)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1dc742-1e5f-dbb1-df52-b7da9a5b41ce
* Version Independent ID: 54dcd81d-86a7-10ca-5f82-a003284e237b
* Content: [Touch Manipulations - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @scastria 

Because graphics programming is complex, the SkiaSharp docs have been written from the perspective that the reader has a solid understanding of both Xamarin.Forms and OOP. Hence the advanced level of the touch manipulations doc. We'll look at this again when this doc is updated.

As an FYI, it's currently possible to do (1) and (2) using Xamarin.Forms (without SkiaSharp), and (3) will soon be possible.
