### ISSUE TITLE
Hyper-V

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#692]
In section 4 for Hyper-V should it be added that you should remove HAXM from extras? 
Some people probably have it installed from before and while it's on, the emulator performance was really bad in my case. When I removed HAXM from extras emulator sped up a lot. 
Also is there a way to verify that emulator is running with Hyper-V instead of HAXM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @domagojmedo, thank you for the feedback! We're in the process of updating this topic and we'll look into your observations -- in theory, it shouldn't be necessary to uninstall HAXM from extras (you may be running into other problems that will be added to a new Troubleshooting section). Also, if there is a way to verify that the emulator is running with Hyper-V instead of HAXM, we will include this information in the topic.

**Comment by domagojmedo** [comment]
@mgmclemore 
Hi, is there a way to verify that the emulator is running with Hyper-V instead of HAXM?
