### ISSUE TITLE
Xamarin.Android in .Net API Browser isn't actual

### ISSUE THREAD

**Issue by ticotaco72** [MicrosoftDocs/xamarin-docs#726]
Link to article: https://docs.microsoft.com/pl-pl/dotnet/api/?view=xamarinandroid-7.1

Version 8.0 is already available for devs, but there's no documentation for it.
MicrosoftDocs/feedback#645
I think that maybe this is better place for this issue.

**Comment by conceptdev** [comment]
Thanks for your feedback. The [link](https://docs.microsoft.com/pl-pl/dotnet/api/?view=xamarinandroid-7.1) you provided above is to the Base Class Library available in Xamarin.Android. Although there is still only documentation for 7.1, the BCL does not change a lot between Xamarin.Android versions, so that documentation is still quite current.

The _Xamarin.Android SDK reference_ is hosted at
https://developer.xamarin.com/api/root/MonoAndroid-lib/
so that is where you should look for Android-specific (ie. non-BCL) APIs. We are planning to migrate that information to docs.microsoft.com in future, and also to ensure it is up-to-date.

For now, for the most up-to-date information on Android API reference, I recommend also referring to Google's [Android API reference](https://developer.android.com/reference/).
