### ISSUE TITLE
Cannot intercept push notification in iOS Notification Service Extension.

### ISSUE THREAD

**Issue by RazvanEmilR** [MicrosoftDocs/xamarin-docs#750]
Hi, I followed the tutorial as described above but I cannot get the Notification Service Extension method DidReceiveNotificationRequest(UNNotificationRequest request, Action&lt;UNNotificationContent&gt; contentHandler) to trigger. I used the correct bundle name www.company.appname.extension and also regsistered with this as the notification template:
const string templateBodyAPNS = @"{
	                                            ""aps"" : {
		                                            ""alert"" : ""$(messageParam)"",
		                                            ""mutable-content"": 1
	                                            },
	                                            ""encrypted-content"" : ""somecontent""
                                            }";

This is driving me crazy. Is there any known issue about this not working in Debug mode on Xamarin?

I've been looking up the issue and some have said that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2ee7c5-fd5e-3c28-31d8-e01820850feb
* Version Independent ID: 5b886a57-3d74-57a7-7726-a740f1efb328
* Content: [Enhanced User Notifications in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications?tabs=vswin#working-with-service-extensions)
* Content Source: [docs/ios/platform/user-notifications/enhanced-user-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/user-notifications/enhanced-user-notifications.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @RazvanEmilR,

Sorry to hear this isn’t working for you. I see you’ve found [a previous discussion](https://github.com/MicrosoftDocs/xamarin-docs/issues/46#issuecomment-419225155) on this topic; hopefully the suggestions there are helpful for you.

In the meantime, as is mentioned on the other thread, this doc is on our backlog to review and update for accuracy.

If you believe you’ve found a bug (as opposed to a docs-related issue), please start a thread on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) by selecting the **Report a Problem** option in [Visual Studio 2017](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) or [Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem), or use the **Product Feedback** button in the docs.

Since we’ve already captured this action item on an internal backlog, I’m going to close this issue. However, again, we will review this doc. Thanks for your calling it out.

**Comment by RazvanEmilR** [comment]
Thanks @bradumbaugh
