### ISSUE TITLE
Throws Origin Null not allowed by Access Control Allow Origin.

### ISSUE THREAD

**Issue by NaveedShaikh** [MicrosoftDocs/xamarin-docs#764]
Hi,
I consumed a POST request using WebView in Xamarin.Forms making required CORS changes at the server end and was able to successfully consume the service. Now when I try to hit the same HTML file containing JavaScript code to execute the request, it throws me the CORS error. Upon investigating, I found it was sending Origin as NULL and Accept as */* in the request parameter, which I believe is causing the issue. This is really weird as the same HTML file works at one place and throws the error at the other. Kindly Help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Implementing a HybridWebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by AlastorReach** [comment]
Hello, I would like to know if is possible to implement this with a razor cshtml page instead of normal html page. I have tried a lot trying to implement javascript on webview and it still haven`t worked. Now I am going to try implementing this but my priority is to do this with a razor view because I get data from Wordpress API and then I need to show it on a Webview, but I need to implement javascript on it but it only works with alerts, no DOM element could be grabbed. (sorry if something is wrong with my English text.

**Comment by conceptdev** [comment]
Unfortunately we cannot respond to support questions here; these issues are for tracking documentation feedback. Other channels you can use to seek help include [Developer Community](https://developercommunity.visualstudio.com/), the [Xamarin Forums](https://forums.xamarin.com/), and [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin).
