### ISSUE TITLE
Need to specify that emulator cannot use Google Play

### ISSUE THREAD

**Issue by valdetero** [MicrosoftDocs/xamarin-docs#769]
The android emulator can be x86 or x86_x64, can use Google APIs or not, but CANNOT use Google Play Store. Running `adb devices` with a Google Play Store emulator running, will return "unauthorized" on the windows machine and you won't be able to connect to it. Please update the docs to reflect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1f18a79-b816-649f-a176-550f6a24e38b
* Version Independent ID: e13cb8db-84f8-d8f5-1073-3c29a9ea2f51
* Content: [Is it possible to connect to Android emulators running on a Mac from a Windows VM? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/connect-android-emulator-mac-windows)
* Content Source: [docs/android/troubleshooting/questions/connect-android-emulator-mac-windows.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/connect-android-emulator-mac-windows.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by JonDouglas** [comment]
@valdetero Google Play Store is only available on a subset of devices such as Pixel, Pixel 2, Nexus 5X, and Nexus 5. Although you can create Play Store emulators with other device configurations, at runtime you can run into issues. Are you using one of these device skins?

This issue seems more like a configuration issue. Once you have the emulator running, `adb devices` should return the emulator process in a ready state. `Unauthorized` typically indicates a missing RSA fingerprint, a mismatch of `adb` versions, or the device does not have USB debugging enabled (on by default for emulators). 

I personally only run Google Play Store emulators locally and share them via `adb connect` between Mac / Windows.

Do you still run into this issue today?

**Comment by valdetero** [comment]
@JonDouglas I am using the Pixel emulator. I have two emulators identical except one has "Google Play Store" checked and I still have that issue today. Now that I figured out that was the issue, I only have one of those and only use it from the Mac if needed.

**Comment by jgold6** [comment]
@JonDouglas I can verify what valdetero has said. I ran into the same issue trying to connect to an emulator on Mac from a Windows machine, and I could only do it with an emulator that did not have Google Play Store.
