### ISSUE TITLE
 I can't intercept push with notification service extension on Xamarin IOS 

### ISSUE THREAD

**Issue by Sennocard** [MicrosoftDocs/xamarin-docs#770]
Hello, I have been trying for a few days to intercept the remote push by Amazon SNS using the notification service extension, here's what I did:

1 - I created a solution with an "Example" project and a Notification Service Extension project "ExampleServiceExtension" following the example
2 - I created in Apple the certificate and provisioning of "Example" and "ExampleServiceExtension"
3 - I used the bundle identifier "com.test.example" and "com.test.exampleserviceextension" for each project
4 - I ran in release mode on iPad and sent a push through amazon (with the mutable-content: 1) 

After all of this, it continued looking like a normal push, not modified by the notification service extension.

Anyone has any idea how to help me?

Best

**Comment by conceptdev** [comment]
Hi @Sennocard, unfortunately we cannot respond to support questions here; these issues are for tracking documentation feedback. Other channels you can use to seek help include [Developer Community](https://developercommunity.visualstudio.com/), the [Xamarin Forums](https://forums.xamarin.com/), and [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin).

Because you are using an Amazon feature, you might also find help in [their docs](https://docs.aws.amazon.com/sns/latest/dg/welcome.html) or support.
