### ISSUE TITLE
Error Timeout exceeded 

### ISSUE THREAD

**Issue by sayedzakrea** [MicrosoftDocs/xamarin-docs#800]
the code works fine at the first choose and if i try to choose image again i get the following error: 
on this line code 
taskCompletionSource.SetResult(stream);
the error message
System.InvalidOperationException: &lt;Timeout exceeded getting exception details&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Picking a Photo from the Picture Library - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sayedzakrea 

I was able to repo this issue and it's caused by not unregistering the callback for the `FinishedPickingMedia` event. This event is raised each time you pick a photo, but the `TaskCompletionSource` associated with it can only be completed once. The solution is to unregister the `FinishedPickingMedia` callback before completing the `TaskCompletionSource`. That way the specific callback associated with the specific `TaskCompletionSource` will never be called again.

I've updated the sample and a doc update is forthcoming.
