### ISSUE TITLE
Could not load type 'Xamarin.Forms.Xaml.IReferenceProvider' 

### ISSUE THREAD

**Issue by danbord** [MicrosoftDocs/xamarin-docs#893]
When I try to display embedded image from Xaml using the ImageResourceExtension provided, it compiles but gives error "Could not load type 'Xamarin.Forms.Xaml.IReferenceProvider'" when starting the probject (in UWP).

Also, It would be nice to explain when/why (in which scenario) we should use local images over embeded images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @danbord 

I just tried the [sample](https://developer.xamarin.com/samples/xamarin-forms/WorkingWithImages/) the doc links to and the embedded image displays fine on UWP. I'm using the latest Windows 10 and VS2017 releases.

As for when to use local images over embedded, it's really about when they need to be different resolutions on different platforms, or have to otherwise be edited for that platform (i.e. a black tick image is fine on iOS as the default app background is white, but used to be problematic on Android when the default app background was black). I'll take a look at the doc.
