### ISSUE TITLE
Useless Xamarin Android P Minidemo

### ISSUE THREAD

**Issue by kurtcz** [MicrosoftDocs/xamarin-docs#895]
Your Xamarin Android P Minidemo is trying to introduce working with the display cutout area but completely misses the mark. You claim that to use the cutout area of the screen you have to

`Window.Attributes.LayoutInDisplayCutoutMode = LayoutInDisplayCutoutMode.ShortEdges;`

Well that is only a half of the story. The only effect the above line has is changing the cutout area color from back to white. How useful is that I ask you? If you want to be able to draw your own content you also have to:

`Window.AddFlags(WindowManagerFlags.TranslucentStatus);`

This information is almost impossible to find though. Please update this demo page to stop confusing the developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b11df82-abfb-85bb-36d0-e48c5f82c02e
* Version Independent ID: 109c5eac-2fb0-218d-b737-d244b45556a4
* Content: [Android 9 Pie - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/pie#feedback)
* Content Source: [docs/android/platform/pie.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/pie.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
@kurtcz I apologize if our documentation mislead you. The `ShortEdges` cutout method has further documentation that explains what is happening:

https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES

Basically the `ShortEdges` cutout mode is extending the window into the cutout areas, which is why you see the area change from black to white, as the content of the app is being extended. Additionally there are some tips of when using `ShortEdges`, what best practices one should follow:

https://developer.android.com/guide/topics/display-cutout/

Do you have further recommendations as to what we can add to this demo to make it less confusing? The behavior seems to remain consistent with what is documented by Google.
