### ISSUE TITLE
Consuming WCF service throws error

### ISSUE THREAD

**Issue by stuixner** [MicrosoftDocs/xamarin-docs#919]
I downloaded this project and tested it on an Android device. When I press one of the buttons, the following error get's catched by the try-catch block in "GetHelloWorldDataButtonOnClick":
(translated from german)
Error deserializing the body of the request message for GetHelloData operation. OperationFormatter has an invalid message body. It is expected to find the node type "Element" named "GetHelloData" and namespace "http://tempuri.org/". It found node type Element with the name "GetHelloDataAsync" and namespace http://tempuri.org/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6d6bd0-71b7-f141-2eed-9f99e5d30099
* Version Independent ID: 37b4dd5f-4f41-d850-6be1-be92fcb3b739
* Content: [Walkthrough - Working with WCF - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf)
* Content Source: [docs/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by moginheden** [comment]
This post will start as a bit of a rant, then go on to show you how to fix the problem.

This is something that should be very easy for developers to use, and probably used by most apps as calling home to a server is a VERY common requirement.... Unfortunately it's currently a bit of a nightmare where a new developer has to go way too far down the rabbit hole of code that should be abstracted away in 2018.  This has been broken for almost a year now and that is NOT acceptable.

Finding how to fix it is also a bit of a mess as the details are NOT included in the official documentation, and there are forum posts all over the place of people asking how to do this.  Can we PLEASE get this fixed by the visual studio/xamarin team? The wizard to import a service should produce working code with no networking or internal implementation knowledge required.

These files show most of the alterations needed to the auto-generated code to get it working for both android and ios. (Ignore the ios on the filename. The code involved should be added to all projects)
https://github.com/sami1971/SimplyMobile/blob/master/Core/Plugins/Stocks/SimplyMobile.Plugins.WcfStockService/StockQuoteServiceClient.cs
https://github.com/sami1971/SimplyMobile/blob/master/Core/Plugins/Stocks/SimplyMobile.Plugins.WcfStockService/StockQuoteServiceClient.iOS.cs

The References.cs code the wizard produces has a class that implements ClientBase.  It needs to be altered in the following ways:
1.) Setup the default EndpointAddress and BasicHttpBinding based on the url entered into the wizard, and some default sane values, (provided in linked code.)
2.) Implement functions that are named EXACTLY the same as the WCF's provided ones in addition to the async ones that it currently makes. (in example code this shows as both GetStockQuote AND GetStockQuoteAsync) (Changing the name of functions in someone else's API is a TERRIBLE policy and also breaks the code to import many android libraries.)
3.) Override the CreateChannel function and make it point to a new class that implements ChannelBase
4.) In the ChannelBase implementing class generate functions for BOTH the original function name AND the Async version.
5.) The linked code uses Invoke that does not exist anymore.  Use the following code as a guide instead:

    public returnType getThingFromServer(string paramNameGoesHere, string param2, int param3)
    {
        IAsyncResult result = BeginInvoke("getThingFromServer", new object[] { paramNameGoesHere, param2, param3}, null, null);
        result.AsyncWaitHandle.WaitOne();
        return (returnType )EndInvoke("getThingFromServer", new object[] { paramNameGoesHere, param2, param3}, result);
    }


With these fixed, users can call use the wizard to connect to a service as if it was a local class without needing to know implementation details or using command line parameters. (Presuming they turn off the broken "reuse types in referenced assemblies" option.)

**Comment by conceptdev** [comment]
Thanks for the feedback and detailed response. We'll be considering this for the next update of this doc.

**Comment by davidbritch** [comment]
This issue has  since been dealt with, so I'm closing it.
