### ISSUE TITLE
Missing Step for a new Mac

### ISSUE THREAD

**Issue by kieronlanning** [MicrosoftDocs/xamarin-docs#976]
Remember to open Xcode to let it install additional components.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Pair to Mac for Xamarin.iOS Development - Xamarin](https://docs.microsoft.com/en-gb/xamarin/ios/get-started/installation/windows/connecting-to-mac/)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Great suggestion, updating the doc now.

**Comment by mstancombe** [comment]
I had this exact same problem, and checked each step by step, and still missed it.. I think 'open xcode on the build mac' deserves to be a first class step in the guide, rather than a purple warning that can be overlooked easily.  I know.. it's on me for not reading carefully, but it does highlight that the numeric steps is a better place for this on a page that is focussed on following numeric steps.
