### ISSUE TITLE
Zh-cn translation of Enterprise Application Patterns Using Xamarin.Forms

### ISSUE THREAD

**Issue by zhenweied09** [MicrosoftDocs/xamarin-docs#999]
Hi guys,
I am currently reading the Enterprise Application Patterns Using Xamarin.Forms eBook and  I am wondering if I can commit new zh-cn translation. After reading the contributing guidelines, I think I should ask for permission here since there might be big changes to the existing translation. 

So please let me know if can do that. Thanks!

**Comment by conceptdev** [comment]
Hi @zhenweied09 thanks for asking! I will pass on your question to the localization team, and respond here.

**Comment by conceptdev** [comment]
Hello again,

We would be happy for you to propose improved translations. As I'm sure you know, the PRs should be made against the https://github.com/MicrosoftDocs/xamarin-docs.zh-cn repo.

Our linguistic team will review your PRs, and merge if accepted.

I suggest doing multiple PRs (maybe one per page) rather than doing one "big" effort. Also, maybe start with a relatively small one first, and get that published, to get used to our system before doing a lot of work.

Thanks again, I'm really excited to see this content get improved for Chinese readers.

-Craig

p.s. I will close this issue now, but if you have questions, feel free to continue to post here; or ping me @conceptdev on your PRs or new issues.
